### ISSUE TITLE
Flashlight doesn't turn on after returning from scan result

### ISSUE THREAD

**Issue by pingu8007** [markusfisch/BinaryEye#101]
# How to reproduce
1. open BinaryEye and switch to a camera with flashlight
2. turn on flashlight
3. scan anything, results are shown and flashlight goes off
4. press 'Back' to viewfinder

# What I expected
After returning to viewfinder, one of the following should happen
1. the flashlight should restore to last status, i.e. it should be on.
2. the flashlight switch should be reset to off

# What I experienced
Neither the flashlight turned on, not the switch reset to off.
I have to press the switch twice to get flashlight turned on again.

# Version info
Version: 1.23.0 (Google Play)
Tested with:
- Google Pixel 3 (G013B) (Android 10 w/ 20200205 patch (QQ1A.200205.002))
- Essential Phone PH-1 (Android 10 w/ 20200105 patch (QQ1A.200105.007))

**Comment by markusfisch** [comment]
Thanks for the details report! 👍 Fixed in https://github.com/markusfisch/BinaryEye/commit/b640fa13725ec76df7e871dfa78d19b9f16bbcdc
