### ISSUE TITLE
Support for inverted barcodes

### ISSUE THREAD

**Issue by Mhowser** [markusfisch/BinaryEye#103]
It would be very handy for Binary eye to support inverted barcodes, perhaps a quick toggle option somewhere.

**Comment by markusfisch** [comment]
It already does, please check:
![sample-qr-code-inverted](https://user-images.githubusercontent.com/485246/77085619-e1428a00-6a00-11ea-9c1e-3b4ae8de7a39.png)

**Comment by Mhowser** [comment]
Works, thank you!
