### ISSUE TITLE
Feature request: Allow scan intent which does not save the barcode in the history

### ISSUE THREAD

**Issue by l-jonas** [markusfisch/BinaryEye#105]
see <https://github.com/markusfisch/BinaryEye/blob/master/app/src/main/kotlin/de/markusfisch/android/binaryeye/activity/CameraActivity.kt#L454>

In my use case, I want to scan a barcode from my application but I don't want it to be put into the scan history (think of a barcode for a one time authentication, although no big issue, it's better if it's not kept at the device). For this, an additional intent extra for com.google.zxing.client.android.SCAN which skips the saving would be very useful.

**Comment by markusfisch** [comment]
Hm, would you want to always skip saving for com.google.zxing.client.android.SCAN or just sometimes? And if sometimes, how would you want to control that? 🤔 

Indeed, I'm not sure if it's best (for everyone) to save the barcode from com.google.zxing.client.android.SCAN at all. So I should definitely add an option in settings to control that.

**Comment by l-jonas** [comment]
I would always skip it.

Background idea: For regular scanning (of a URL or whatever), the user opens the scanner directly. Scanning is e.g. used in the Pix Art Messenger (which has its own scanner, but assume it would use a scan intent for the example) for adding a contact and validating its fingerprint. However, in this case the application does things with the content so there is no need to save it outside of it. Another aspect is that the user can currently not replay the barcode at another scan intent (without putting the code from the history to an other device).

So I would never record them. Eventually, there are other use cases where saving them is still useful, but I don't know of any.

Alternatively, I could think of an intent extra for a opt in or a opt out of the history.

**Comment by markusfisch** [comment]
I think you're right. The app shouldn't save barcodes that are meant for other apps.

Changed in https://github.com/markusfisch/BinaryEye/commit/4bfa7b358240807a5d5cf081b662b960e6dec441, update is coming soon.
