### ISSUE TITLE
Add slide to zoom gesture

### ISSUE THREAD

**Issue by bulvvko** [markusfisch/BinaryEye#107]
Using a slider to zoom is not very convenient. 
My proposal - use slide to zoom gesture ([like Instagram stories creation mode](https://www.youtube.com/watch?v=lMnymlk6Tr8)) instead using a slider

**Comment by markusfisch** [comment]
Well, that is just a kind of invisible vertical slider, right? 😉But how to zoom back out after we zoomed in?

It sure is an interesting concept, but I'm not really sure if it's as useful as a slider to the average user. How does a user know, he/she can do that gesture? And there would have to be some icon so a user knows where to start the gesture 🤔

**Comment by markusfisch** [comment]
Couldn't resist and implemented it as an alternative to the slider 😉 See  https://github.com/markusfisch/BinaryEye/commit/f08efb8238701cad1b47af71830e89fa11a16581

Will most probably be in the next version.
