### ISSUE TITLE
Scan History

### ISSUE THREAD

**Issue by moriel5** [markusfisch/BinaryEye#11]
Hi, I had just tried out BinaryEye (via F-Droid), and I came away extremely impressed at it's features vs. it's size.
there are two options that in my opinion are missing, though (the others will be in seperate issues).

Could you please add a scan history, with an toggle for enabling/disabling it (the toggle is for those who do not want the history option)?

**Comment by markusfisch** [comment]
Would it be okay if this option is disabled by default?

I would add another menu item on the camera screen that shows a list of past scans.

**Comment by moriel5** [comment]
That would be perfect.
Could you please also add options to remove individual entries, and to clear the entire bistory?

**Comment by markusfisch** [comment]
Yes, had that on my mind too 😉

**Comment by moriel5** [comment]
This is looking to be awesome.
Thank you very much.

**Comment by markusfisch** [comment]
Added in b8cf3a6fe9cdccc959778d755d2bd13143237eb2
