### ISSUE TITLE
Unable to scan

### ISSUE THREAD

**Issue by 11fen** [markusfisch/BinaryEye#115]
![捕获](https://user-images.githubusercontent.com/44218055/81930645-6e7a1780-961b-11ea-8e9e-693b837d5365.PNG)

**Comment by SuperSandro2000** [comment]
This app does not support this type of code.

**Comment by markusfisch** [comment]
Sorry, this is no barcode [ZXing](https://github.com/zxing/zxing) can read, unfortunately.

ZXing is the barcode reading library Binary Eye is using.

To see what barcodes are supported please see https://github.com/markusfisch/BinaryEye#read
