### ISSUE TITLE
Feature Request: add VCALENDAR-events to calendar app

### ISSUE THREAD

**Issue by MikeH6459** [markusfisch/BinaryEye#118]
Thanks for the great app, love it.
I have a hopefully small feature request: Most calendar events are VEVENT type, scanning with BinaryEye and adding them to my calendar app works perfect.

But some barcodes are VCALENDAR type (sorry, don't know if its the right term).
Example:
BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VEVENT
LOCATION:Ort
SUMMARY:Zusammenfassung
DESCRIPTION:Beschreibung
DTSTART:20200608T090000
DTEND:20200609T235959
END:VEVENT
END:VCALENDAR

You can find an online barcode generator [here!](https://www.freeformatter.com/qr-code-generator.html). This was the first one I found, even if the dropdown says VEVENT.
Reading the barcode with BinaryEye works perfect, but there is no option to add in the calendar app as it is with the VEVENT type. Floating button is only offering websearch.
Zxing Barcode Scanner can add them to the calendar, this is literally the only reason this old app is still on my phone.
Sorry if my description is not too precise, I'm just a network guru and sometimes at work I get these kind of barcodes.

Thanks

**Comment by markusfisch** [comment]
Thanks for pointing that out!

I just added support for `VCALENDAR` in https://github.com/markusfisch/BinaryEye/commit/2525b693c7ae470dd20527d2765ed3669cfd598f so it will be in the next version 😄 

Will come available these days.

**Comment by MikeH6459** [comment]
Cool! Thanks a lot!
