### ISSUE TITLE
Front Camera

### ISSUE THREAD

**Issue by moriel5** [markusfisch/BinaryEye#12]
This issue sounds odd (also to me), however it has it's importance.

Can you please add the front camera as an additional scanning source?
This could be of use to those with a broken/nonfunctional rear camera.

**Comment by markusfisch** [comment]
Since it's very easy to do, added in https://github.com/markusfisch/BinaryEye/commit/f29f9e134fe5722a91d1a8d1a2b9d25404da40f6

**Comment by moriel5** [comment]
Thanks.
