### ISSUE TITLE
Question: Is there a limit to scan history?

### ISSUE THREAD

**Issue by RayBB** [markusfisch/BinaryEye#124]
I searched the repo and couldn't find anything related to if there's a limit to scan history. I was just wondering before I go off scanning a bunch of things and find out the hard way.

Thanks so much for making this project it works really great!

**Comment by markusfisch** [comment]
Hi, since the scans are stored in a SQLite database (which is the default database on Android), it's limits are defined as follows:

> Maximum Database Size
>
> Every database consists of one or more "pages". Within a single database, every page is the same size, but different database can have page sizes that are powers of two between 512 and 65536, inclusive. The maximum size of a database file is 2147483646 pages. At the maximum page size of 65536 bytes, this translates into a maximum database size of approximately 1.4e+14 bytes (140 terabytes, or 128 tebibytes, or 140,000 gigabytes or 128,000 gibibytes).
>
> This particular upper bound is untested since the developers do not have access to hardware capable of reaching this limit. However, tests do verify that SQLite behaves correctly and sanely when a database reaches the maximum file size of the underlying filesystem (which is usually much less than the maximum theoretical database size) and when a database is unable to grow due to disk space exhaustion.

From: https://www.sqlite.org/limits.html

So it's probably fair to say the limit is the storage size of your device 😉
