### ISSUE TITLE
Feature Request: Continuous Scanning

### ISSUE THREAD

**Issue by RayBB** [markusfisch/BinaryEye#125]
Current behavior:
After each scan there is a vibrate + popup with information/actions related to the barcode just scanned

Desired behavior:
An option such that:
After each scan, the phone vibrates but allows you to continue scanning without having to hit back.

Use case:
Scanning a lot of books to put into your spreadsheet. All I want is to scan all the codes so I can later export them.

Example: [Barcode Scanner+ (plus)](https://play.google.com/store/apps/details?id=com.srowen.bs.android) had this feature and it worked well. However, the app hasn't been updated in years and is getting slow/buggy. [Screenshot](https://user-images.githubusercontent.com/921217/85232016-0e208780-b3ca-11ea-924e-ca153e4127fa.png)

Again, this project is awesome and so much better than the buggy alternatives loaded with ads.
If you had a donate button (especially if I can use my google credits) to support your work I would definitely use it :)

**Comment by markusfisch** [comment]
This feature will come with the next version 😄

**Comment by markusfisch** [comment]
Implemented in https://github.com/markusfisch/BinaryEye/commit/9d1dec146dfa6cef0ea52a447430ea84d64a4653

In Version 1.32.0, there's a new menu item "Scan continuously" in the camera screen now.

Will become available soon in beta (you can go back to production at any time):
https://play.google.com/apps/testing/de.markusfisch.android.binaryeye

Or directly from here:
https://github.com/markusfisch/BinaryEye/releases/tag/1.32.0
