### ISSUE TITLE
Dragging the crop icon far bottom right crashes the app.

### ISSUE THREAD

**Issue by jtagcat** [markusfisch/BinaryEye#127]
My navigation buttons are software, dragging the icon under the navigation far right, crashes the app reproducably.

Probably something to do with it being out of the screen (technically..ish).

**Comment by markusfisch** [comment]
Thanks you for reporting this bug! 👍 

I've just fixed it in https://github.com/markusfisch/BinaryEye/commit/4f1482d2c9d32305058ad259e29726193df511d6

A new version will become available shortly.

**Comment by jtagcat** [comment]
Commending on the _fucking fast_ issue closure!
