### ISSUE TITLE
FR: Option to copy scanned barcode automatically

### ISSUE THREAD

**Issue by EyeCon** [markusfisch/BinaryEye#129]
Hello,

I really like BinaryEye and want to thank you for it. Especially the raw view is useful for me.

Would it be possible to add an option to copy the scanned code to the clipboard? I might have missed it, but couldn't find it in options. This is the only thing I miss from the default barcode scanner. An action to share/save the raw dump could be useful too.

Thanks again!

**Comment by markusfisch** [comment]
Hi,

there should be an action item with which you can copy the contents of the scanned barcode in the toolbar at the top of the screen:
![screencap-20200711152533](https://user-images.githubusercontent.com/485246/87225116-f87bfd80-c38a-11ea-8924-1388f2488104.png)

Is it somehow missing on your device? Or maybe hidden in an overflow menu (there are just three vertical dots in the top right corner of this screen)?

Right next to the copy item should be a share item with which you can share the contents of the scanned barcode.

If the barcode contains binary data, you can save this raw data in a file by using the floating action button in the lower right corner of the screen (it'll show a save icon in this case).

**Comment by EyeCon** [comment]
It does, and I use the button. I meant an automatic copy-on-scan feature.

I didn't know about saving binary data, I will try it out.

**Comment by markusfisch** [comment]
Ah, understood! 🙈 This is really quite easy to add so expect it to come with the next version 👍

**Comment by EyeCon** [comment]
Wow, thanks a lot!

**Comment by EyeCon** [comment]
I just got the new version with the feature, thank you again!

**Comment by markusfisch** [comment]
You're welcome 😄 And thanks for using Binary Eye!
