### ISSUE TITLE
Scanning From File

### ISSUE THREAD

**Issue by moriel5** [markusfisch/BinaryEye#13]
Could you please add scanning from an existing file as a source?

In any case, Binary Eye is awesome.
Thanks for your hard work!

**Comment by markusfisch** [comment]
Yes, will come! That's a feature I wanted to add for some time now.

**Comment by markusfisch** [comment]
Added in https://github.com/markusfisch/BinaryEye/commit/b19d2b1894bcd81934fb135176e2ae1cfc5fec1e

**Comment by Wilker-a** [comment]
sorry if it's not released yet, but where do i find this option in 1.13.1? i can't seem to find it myself \^\^'

**Comment by molikuner** [comment]
Just open the image in your gallery app and "share" the picture with BinaryEye.

**Comment by Wilker-a** [comment]
oh, okay, thank you \^\^

i think that a small button in the menu to `read from file…` would be useful to add :3

**Comment by moriel5** [comment]
Thanks, this is awesome.
I guess I can close this issue now?
