### ISSUE TITLE
Flag to toggle automatic data display

### ISSUE THREAD

**Issue by deliciouslytyped** [markusfisch/BinaryEye#132]
This would be a companion to https://github.com/markusfisch/BinaryEye/issues/95#issuecomment-661631422 , 
it gets in the way if I have to press "back" every time I scan a code, so it would be helpful to have one or any of these options:
- turn off automatic the data display
- have a split screen mode where you can keep scanning and using the camera
- show the data via some other on screen notification

**Comment by deliciouslytyped** [comment]
Ok, I figured out that the option is "skip inspection and open contents immediately". This is somewhat helpful, but it still opens the inspection dialog in the background so you still have to back out of it to scan the next item.

**Comment by markusfisch** [comment]
I think you want the bulk mode which is available in the overflow menu as "Scan continuously". In this mode, Binary Eye just keeps on scanning after a barcode was detected and just shows a Toast with the contents.

**Comment by deliciouslytyped** [comment]
Sorry, I found the bulk mode, I was still on 1.31.0 .
