### ISSUE TITLE
QR error correction level

### ISSUE THREAD

**Issue by JonnyTech** [markusfisch/BinaryEye#136]
In notice that QR codes are generated with an error correction level of `L`: low 7%.

Can you possible add an option to set the other standard ECL's please?

`M`: medium 15%
`Q`: quartile 25%
`H`: high 30%

Thank you in advance for your consideration.

**Comment by markusfisch** [comment]
Sorry for the late answer. Yes, that's possible, of course 👍 

It'll be in the next version.

**Comment by JonnyTech** [comment]
Wow, fantastic, thank you very much indeed.

**Comment by markusfisch** [comment]
Implemented in https://github.com/markusfisch/BinaryEye/commit/18146ec41a4c0830037b0992e1bc6be73145bc0c
