### ISSUE TITLE
Compose to ASCii QR code

### ISSUE THREAD

**Issue by Mhowser** [markusfisch/BinaryEye#139]
There is this cool site that can generate QR codes using Unicode characters http://asciiqr.com/index.php

I was wondering if this can be ported over to your app. Source code here: http://asciiqr.com/source.txt

This would be quite useful since some sites don't allow image posting.

**Comment by markusfisch** [comment]
Yes, this is surely possible! And it's quite interesting too 😉 

I really might add such a feature in one of the next versions 🤔  Thanks for pointing me at this 👍

**Comment by Mhowser** [comment]
Thank you!

**Comment by Mhowser** [comment]
Also i was wondering if this could be extended to DataMatrix and Aztec Codes as well.

**Comment by markusfisch** [comment]
Added in c5cffc00c3253cee5c6f45e20fa298d07b9721e5 :smile:

Will come with the next release.

**Comment by Mhowser** [comment]
Wow thank you so much!
