### ISSUE TITLE
Please make shourcut icons adaptive

### ISSUE THREAD

**Issue by 532910** [markusfisch/BinaryEye#143]
![image](https://user-images.githubusercontent.com/14617699/96518077-bfe59d00-1272-11eb-9acb-4f212d078c98.png)

Known apps with adaptive shortcut icons:
[Element](https://github.com/vector-im/element-android), [Orgzly](https://github.com/orgzly/orgzly-android), [Calendar](https://github.com/LineageOS/android_packages_apps_Etar), [SELinuxModeChanger](https://github.com/MrBIMC/SELinuxModeChanger), SoundCloud
![image](https://user-images.githubusercontent.com/14617699/96517260-4ef1b580-1271-11eb-8723-448ca6413dc2.png)

All of these shortcuts are created the same way, via long press from the main icon and dragging it to the desktop.

**Comment by markusfisch** [comment]
Added in 5cd6114ba1b0e4c4717500b6dc61be624ef4c351 :smile:

**Comment by 532910** [comment]
Fixed, thank you!
