### ISSUE TITLE
Feature Request: Add an option to "Go back to main screen, when <copy> was hit"

### ISSUE THREAD

**Issue by klawdhfzasjhaa** [markusfisch/BinaryEye#154]
Mostly I scan a code and copy it to another app or my desktop via KDEConnect. When I open BinaryEye the next time, the previously scanned barcode output is still shown. Instead, the app should be ready to the main / scan screen to be ready to scan, when the app is used the next time.

**Comment by markusfisch** [comment]
I see. Yes, that makes sense 👍  I will add an option for this.

**Comment by markusfisch** [comment]
Implemented in https://github.com/markusfisch/BinaryEye/commit/8df09090c97e74db3570f22f15b570a63791a1ec

Will release soon 😉
