### ISSUE TITLE
Remove BOM (byte order mark) before copying to clipboard

### ISSUE THREAD

**Issue by itc-ger** [markusfisch/BinaryEye#157]
I just experienced an issue with QR codes whose text includes a BOM (byte order mark) at the beginning of the string.
e.g. text is `hello` (hex:  `68 65 6c 6c 6f`) was (utf8) qr encoded as `ef bb bf 68 65 6c 6c 6f`.

In this case I just wanted to copy only printable chars to the clipboard, I expected the BOM to be removed.

As I understand the removal of non printable chars might be unwanted in some cases, I would suggest an optional filter for those BOM values (https://en.wikipedia.org/wiki/Byte_order_mark#Byte_order_marks_by_encoding).

So could you consider to implement such an optional BOM-filter in Binary Eye, please?

**Comment by markusfisch** [comment]
Hm, yes, I would like to offer such a filter, but I don't know how exactly yet 🤔 

What did Binary Eye show?  `68 65 6c 6c 6f` or `ef bb bf 68 65 6c 6c 6f`?

Do you have an example QR Code featuring a BOM?

**Comment by itc-ger** [comment]
This issue was solved by an update long time ago, so I think we can close this ticket.
