### ISSUE TITLE
Use HttpsURLConnection inside ScanSender.kt

### ISSUE THREAD

**Issue by STPR** [markusfisch/BinaryEye#158]
Hello,

Is it possible to use HttpsURLConnection inside ScanSender.kt instead of HttpURLConnection ?
[https://developer.android.com/reference/javax/net/ssl/HttpsURLConnection](https://developer.android.com/reference/javax/net/ssl/HttpsURLConnection)

**Comment by markusfisch** [comment]
Hi, `https` is already supported using the code as it is.

Simply use URL that starts with `https://…` to send scans encrypted 😉

**Comment by STPR** [comment]
I've already tested that but HttpURLConnection class supports only HTTP/1.1
What I would like is the support of HTTP/2
But I don't know if HttpsURLConnection supports it.

**Comment by markusfisch** [comment]
The protocol version of HTTP has nothing to do with `HttpsURLConnection`. `HttpsURLConnection` just adds an encryption layer around the HTTP protocol.

As far as I know, Android's `URLConnection` family does not support HTTP/2 at this moment. To support HTTP/2, we would need to use a different HTTP client like [OkHttp](https://github.com/square/okhttp) - which would add a dependency and would make the app bigger. So, what would we gain by supporting HTTP/2?

**Comment by STPR** [comment]
Ok, so it's preferable to wait until Android support HTTP/2.
