### ISSUE TITLE
Saving generated code to file

### ISSUE THREAD

**Issue by FredMadison** [markusfisch/BinaryEye#16]
Thanks for this great app (F-Droid release v1.3.8)! Could you please add an option to save a generated code to file (so you can email a code or display a code in a web page, for example)?

**Comment by nemobis** [comment]
I would also like to export a list of all the scanned codes in some way.

**Comment by markusfisch** [comment]
Yes, of course, I had planned something like this already.

Exporting all scanned codes will be very easy as soon as there is a scan history, see #11.

**Comment by markusfisch** [comment]
Added in https://github.com/markusfisch/BinaryEye/commit/242421a765530b2c8b42c5370290188d2ee91a83
