### ISSUE TITLE
Remember the "Scan continuously" setting

### ISSUE THREAD

**Issue by Conder000** [markusfisch/BinaryEye#164]
After turning on (ticking) the "Scan continuously" setting, quiting the app and opening it again, that setting is always turned off (unticked). Please, would it be possible to make BinaryEye remember this setting? Alternatively, a new setting in Preferences to always start with "Scan continuously" turned on would be fine as well.

**Comment by markusfisch** [comment]
Implemented in https://github.com/markusfisch/BinaryEye/commit/636ac2386a6706e08a4e151a0696a5ca4eb948fc

Will be in the next release 😄
