### ISSUE TITLE
Feature request: Generate barcodes

### ISSUE THREAD

**Issue by savornicesei** [markusfisch/BinaryEye#165]
Hi all,

I am using BE to test scanning feature of an another android app that runs in an emulator (emulator camera is set to use the real camera of the laptop).
I usually have the barcodes as numbers so I can generate the barcode in BE and "show" it to my laptop camera. This works great!
But sometimes I need new barcodes - and while there are websites that provide this feature it would be much secure and private to have them generated by BE since I can easily share them with my laptop through KDE connect.

As a developer (not an android one) I'm wondering if it's an easy thing to do or what complexities might be hidden in such feature.

Thank you for this awesome app!

**Comment by markusfisch** [comment]
Hi, and thanks for using Binary Eye 😄 

So you would like the app to generate barcodes remotely? Well, I'm not familiar with KDE connect but if the Android part can share some text via Android's share menu, you'd be able to use that to generate a barcode.

**Comment by savornicesei** [comment]
Hi,

No. Just to generate them in-app. Then I can use the share feature in BE to move them to my computer through KDE Connect.

**Comment by markusfisch** [comment]
Sorry, I still don't quite understand 🙈 How should that button generate a "barcode number, based on the selected format"?

Let's say the selected format is QR Code. Now what should that button generate? A serial number? That gets incremented with every button press?

**Comment by savornicesei** [comment]
The QR code could be generated by some text entered by user (could be a link to something).
For the 'classic' barcodes, for example EAN13 - the numbers must follow some check rules for the barcode to be valid. This is the scenario I'm interested in and in the end I think it's enough to be able to disable the numbers check when generating the barcode image.

Does it make sense?

**Comment by markusfisch** [comment]
Hm, these checks aren't part of my app but come from the ZXing library itself. See, some barcodes are _designed_ for numbers. They _can't_ express anything else.

For example, see: https://en.wikipedia.org/wiki/International_Article_Number

**Comment by savornicesei** [comment]
Ahhh, got it. Thank you.
