### ISSUE TITLE
Fastlane directory uses invalid names for some locales

### ISSUE THREAD

**Issue by linsui** [markusfisch/BinaryEye#169]
[Fastlane](https://github.com/fastlane/fastlane/blob/633860a5aae0fa9c0b936797560efb24181b1bf7/fastlane_core/lib/fastlane_core/languages.rb#L14) uses [BCP47](https://www.w3.org/International/articles/bcp47/) locale tags without `r`. Please rename those dirs. Thanks!

For reference: F-Droid downstream [issue](https://gitlab.com/fdroid/fdroiddata/-/issues/2323).

**Comment by markusfisch** [comment]
Done in https://github.com/markusfisch/BinaryEye/commit/fb96d5ecf805bbd6a17cb7e9f06d48457969066f
