### ISSUE TITLE
Could you add a function to insert a small picture in the middle of the QR code?Thanks a lot

### ISSUE THREAD

**Issue by bitbangonline** [markusfisch/BinaryEye#170]

**Comment by bitbangonline** [comment]
your app is preety ......good

**Comment by markusfisch** [comment]
Yes, this would be possible, but I'm afraid it's a little beyond the scope of this app 😬 One can always change the generated image in another app.

And putting an image on a barcode would probably only make sense with QR Codes 🤔 Hmm, I'm thinking about it 😉

**Comment by bitbangonline** [comment]
Yes  I am talking about the qrcode  and now most of the qrcode will have a picture on it  so that people may be More assured to Scan it

**Comment by bitbangonline** [comment]
A small squared Picture in the middle of the QR Code，I'm very happy that you can join this feature😁 Because what we use most in our daily life is QR Code

**Comment by OverkillGuy** [comment]
As someone who dug in the [qrcode.com](https://www.qrcode.com) website (owners of the QR Code patents) a lot for research purposes, I would point out [this piece of their FAQ](https://www.qrcode.com/en/faq.html#qrcodeH2Title) (emphasis mine):

> ### It is all right to use QR Codes with colors or an inserted illustration?
> Users of QR Code must be careful about deforming the code by overlaying it with an illustration or putting a a design on it. If it is deformed, the QR Code's error correction function is invoked where even a tiny missing or smeared part renders the reading operation impossible, or the response of the operation may become slow. DENSO WAVE recommends that you use the QR Code following the specifications in the JIS or ISO standard to assure stable reading of the QR Code. Furthermore, if the QR Code is overlaid with an illustration or design, the resultant code may not be called a QR Code any longer, because there is no standard for doing this kind of operation. **Although DENSO WAVE waives its rights to QR Codes as long as they follow the JIS or ISO standard, this is not necessarily the case with codes that do not follow the standard. DENSO WAVE may decide to exercise its patent rights against such codes. If you are contemplating arranging an illustration or design involving a QR Code, please consult with DENSO WAVE about your project beforehand.**

As much as I'd love to see that kind of image-inside-QR stuff (perfect for branding purposes!) it's specifically the kind of commercially oriented applications that the company would try to defend (see their product [FrameQR](https://www.denso-wave.com/en/system/qr/product/frame.html) which is exactly this).

I don't know what weight those words may carry for this project, but it felt important enough to mention here.
