### ISSUE TITLE
very difficult to scan if the code is not standard 

### ISSUE THREAD

**Issue by OmlineEditor** [markusfisch/BinaryEye#174]
your program takes a very long time to scan the code. sometimes she gets a scan, sometimes she fails. you can improve the algorithm so that it scans as fast as the program SecScanQR ?
![hard](https://user-images.githubusercontent.com/13348933/111915290-7948d880-8a86-11eb-8edb-701fbcce3630.png)

**Comment by markusfisch** [comment]
Binary Eye does use the [ZXing](https://github.com/zxing/zxing) barcode image processing library to decode QR Codes. So this would rather be an issue for ZXing 😉
