### ISSUE TITLE
There are two QR Codes and I can't scan them with this APP, But I can scan it with 'Wechat',These two conditions are in the same light,The same distance,Using the same cell phone.

### ISSUE THREAD

**Issue by bitbangonline** [markusfisch/BinaryEye#175]
![IMG_20210323_200303](https://user-images.githubusercontent.com/71771386/112144281-f48bc500-8c13-11eb-84ab-4e5e657de29d.jpg)

**Comment by bitbangonline** [comment]
![image](https://user-images.githubusercontent.com/71771386/112144524-4df3f400-8c14-11eb-8171-74e440c05863.png)

**Comment by bitbangonline** [comment]
These two pictures are both qrcode,It's not wechat's code

**Comment by markusfisch** [comment]
Binary Eye uses the [ZXing](https://github.com/zxing/zxing) barcode image processing library for decoding QR Codes. I don't know what WeChat is using or what pre-processing steps WeChat is doing before decoding a QR Code.

The first QR Code on the bottle cap has a very low contrast which may be the reason Binary Eye cannot read it. This can be improved by processing the camera image to enhance the contrast. This is similar to https://github.com/markusfisch/BinaryEye/issues/122

The second QR Code is so heavily garbled that I'm really surprised WeChat can actually decode it 🤔 I doubt ZXing can read this one at all - at least not without heavy pre-processing.

**Comment by bitbangonline** [comment]
scanning by Wechat and scanning by
this APP are under the same light and distance And the same cell phone, so it should not be a problem of camera image😂

**Comment by bitbangonline** [comment]
Could you add some pre-processing procedure?So that your application can be more comprehensive And  Excellent😊

**Comment by bitbangonline** [comment]
> Binary Eye uses the [ZXing](https://github.com/zxing/zxing) barcode image processing library for decoding QR Codes. I don't know what WeChat is using or what pre-processing steps WeChat is doing before decoding a QR Code.
> 
> The first QR Code on the bottle cap has a very low contrast which may be the reason Binary Eye cannot read it. This can be improved by processing the camera image to enhance the contrast. This is similar to #122
> 
> The second QR Code is so heavily garbled that I'm really surprised WeChat can actually decode it 🤔 I doubt ZXing can read this one at all - at least not without heavy pre-processing.

![1617798295487](https://user-images.githubusercontent.com/71771386/114001257-5859f300-988e-11eb-977b-af075a281a7a.png)
this is also can not be scanned, wechat can.it is BinaryEye not ZXing's eye,if ZXing is not excellent,dismiss it and use another one,We can't be limited to the original definition of qrcode, everything is developing😂

**Comment by markusfisch** [comment]
Actually, I can read this image with Binary Eye using a Pixel 2 and a steady hand 😉 But a Fairphone 2, for example, can't. So it depends on the quality of the camera, unfortunately.

Do you know of a good ZXing alternative? One that's free to use and supports as many barcodes as ZXing does? I would definitely switch then! 😉 

I realize people do crazy things with QR Codes - but Binary Eye isn't just a QR Code scanner but a generic barcode scanner that's used for other barcodes as well. So I can't just switch to a decoder that only supports QR Code.

Pictures like this are highly specific. WeChat is focused on just a couple of barcodes and may even be specialized for these highly distorted codes as well.

Binary Eye _could_ be modified to preprocess the camera image to make ZXing read images like this. But this would be a lot of work and could only be beneficial for 2D Codes and bad for 1D Codes. Every specialization comes with a cost. Specializing in a particular challenge can, of course, limit the use case to that challenge and leave the more general cases behind.

That said, I'm guilty of playing with QR Codes in the same way myself 😉 Have a look at this: https://qrim.markusfisch.de/

With the difference that Binary Eye can read these QR codes quite well (depending on the dot magnifier setting) 😉 So I'd rather wish people doing these kinds of codes would choose a more robust configuration.

**Comment by bitbangonline** [comment]
hope it will does well in qr scanning， Nowadays most people use qrcode but not 1d code
