### ISSUE TITLE
Scrambled Language Selection

### ISSUE THREAD

**Issue by ss11mik** [markusfisch/BinaryEye#179]
The in-app language selection is buggy (I didn't figure out how from a quick look at the code) - selecting Simplified Han or Portuguese (Brazil) keeps the app in English, and the option for Czech switches to Japanese :laughing: . Also, option for Japanese is not present at all.

I am using version 1.40.0 from F-Droid.

**Comment by markusfisch** [comment]
Good find! 👍 Fixed in https://github.com/markusfisch/BinaryEye/commit/d890bf28fa4db160ce0768a958b4a00cf485be36
