### ISSUE TITLE
Can't open custom schemes on android 11

### ISSUE THREAD

**Issue by Bubu** [markusfisch/BinaryEye#185]
On android 11 I cannot open a custom scheme url that is registered in an intent filter of another app.

This should be because binary eye is using intent.resolveActivity but has only specified `<queries>` attributes for the http(s) scheme.

See: https://github.com/markusfisch/BinaryEye/blob/master/app/src/main/AndroidManifest.xml#L18

and : https://github.com/markusfisch/BinaryEye/blob/a11650eaa56a5101ebf6f6ddb0c449d414160b48/app/src/main/kotlin/de/markusfisch/android/binaryeye/actions/search/OpenOrSearchAction.kt#L33

(Reference: https://cketti.de/2020/09/03/avoid-intent-resolveactivity/)

I guess there's two options to solve this: just try to launch the intent and see if it works or add QUERY_ALL_PACKAGES permission.

**Comment by Bubu** [comment]
One weird thing I noticed was: it works when scanning `fdroidrepos://` urls which correctly open with fdroid...  it did not work for another scheme and another target app. (maybe the package filterig has special rules for targets that aren't yet targeting android 30? )

**Comment by markusfisch** [comment]
Hm, yes, I see 🤔 I think it's probably best to simply launch the intent and catch any possible exception if it can't be resolved like it's done in [execShareIntent()](https://github.com/markusfisch/BinaryEye/blob/a11650eaa56a5101ebf6f6ddb0c449d414160b48/app/src/main/kotlin/de/markusfisch/android/binaryeye/content/Share.kt#L14).

**Comment by markusfisch** [comment]
Changed in https://github.com/markusfisch/BinaryEye/commit/455d329fff7a04ee5b13d8190543e209c5f490ce

Will be in the next release.

**Comment by markusfisch** [comment]
It's in 1.42.0 which is about to become available on Google Play and F-Droid.
