### ISSUE TITLE
Pop-up window to confirm the save

### ISSUE THREAD

**Issue by OmlineEditor** [markusfisch/BinaryEye#187]
when I have generated the code and click the save button, the image is saved but nothing is shown on the screen that the image was saved successfully or with an error. please add a notification about the successful or unsuccessful saving of the generated image.

sometimes I even click twice and save several images because I don't understand whether I clicked successfully or not.

**Comment by markusfisch** [comment]
Hm, there should already be a notification after saving a barcode 🤔  Please have a look:

https://user-images.githubusercontent.com/485246/117687641-4682ad00-b1b8-11eb-99a3-c9a5bef7784c.mp4

Is "Saved in Downloads" missing on your device?

**Comment by OmlineEditor** [comment]
I deleted the app and installed it again. the message appeared. problem solved. there may have been temporary problems.
