### ISSUE TITLE
Feature suggestion: default search engine

### ISSUE THREAD

**Issue by Shuunen** [markusfisch/BinaryEye#188]
Hi !

Thanks for this super OSS app <3

I'm currently using the `Open immediatly` option : 

![image](https://user-images.githubusercontent.com/439158/117873054-aacc6c00-b29f-11eb-84c4-84e955cff762.png)

When I scan something a popup ask me which search engine I want : 

![image](https://user-images.githubusercontent.com/439158/117873216-d4859300-b29f-11eb-9a45-f6d00d67d925.png)

It would be nice IMHO to be able to set a default search engine to avoid this popup for people like me that choose the same engine on each scan.

What do you think ?

**Comment by markusfisch** [comment]
Implemented in https://github.com/markusfisch/BinaryEye/commit/5740b4356827f6f61b487099425f11d18820b911

1.42.0 should become available soon on Google Play and F-Droid.

**Comment by Shuunen** [comment]
thanks a lot Markus 👍
