### ISSUE TITLE
Post Matrix Code

### ISSUE THREAD

**Issue by white-gecko** [markusfisch/BinaryEye#189]
I don't know of this is the right place. But did anybody try to extract the tracking code (Sendungsnummer) from the new German Post Stamp's Matrix Codes?

That would be a cool feature for Binary Eye

**Comment by markusfisch** [comment]
Hm, what Matrix Code do you mean exactly?
https://www.deutschepost.de/de/f/frankierung/matrixcode.html

Usually, the tracking code/Sendungsnummer is in the last 1D barcode at the bottom of the label. So there wouldn't be no extraction required. At least this is the case with the packages I have available at the moment 😉 Do you have a sample?

**Comment by white-gecko** [comment]
I'm speaking about theses codes: https://www.deutschepost.de/de/b/briefmarke-mit-matrixcode.html

![marke](https://user-images.githubusercontent.com/1018168/118459765-58a2a500-b6fc-11eb-99ca-abc3914d20ed.jpeg)

The binary representation of the matrix code is:
```
44 45 41 35 00 01 A6 92
FE A4 01 00 00 66 09 01
04 25 80 DB 5D 80 21 77
6F EA E4 33 51 DB 84 C7
44 D6 61 7D CB D8 17 85
00 50 00 00 00 00 00
```

The Sendungsnummer is: `A401000066001A692FE8`.

Now that I look at it again I realize, that I find the Sendungsnummer in the matrix code

```
44 45 41 35 00 01 A6 92 FE A4 01 00 00 66 09 01 04 25 80 DB 5D 80 21 77 6F EA E4 33 51 DB 84 C7 44 D6 61 7D CB D8 17 85 00 50 00 00 00 00 00
                           A4 01 00 00 66
             0 01 A6 92 FE
			   8 <- this must be some checksum
```

Last time, the Post app must have scanned a different stamp on the sheet of stamps than the one I have scanned with Binary Eye. So I could not find the full Sendungsnummer in the data matrix. Also some part of the code seems to identify the design of the stamp.

**Comment by white-gecko** [comment]
I also have this one, which is also a different stamp design:

```
444541350006EC6C8DA40100006508040425BA2E90844593A3C55B18A6F4CC703561FCD67D360DC100500000000000
                  A4010000650
          06EC6C8D
                  D
```

**Comment by markusfisch** [comment]
Hm, that's interesting! Nice catch! 👍 

If we could identify and parse it, it would be very easy to add a custom action in Binary Eye.

**Comment by white-gecko** [comment]
Do we need more samples for that?

**Comment by markusfisch** [comment]
> Do we need more samples for that?

Yes, the more the better! 😉 

> And do you have a clue, how the last 4 bits are calculated (is it a checksum)?

Not yet, but it seems very likely to be a checksum. Maybe something like a [Luhn algorithm](https://en.wikipedia.org/wiki/Luhn_algorithm).

**Comment by Alex-Esko** [comment]
I provided the samples for reference only, it was not a request.
But now that you ask: It would be great, if **DHL-Paket** and **Einschreiben** and **Briefmarke mit Matrixcode** could be detected. And then a link for tracking be provided.


**DHL-Paket from DE to DE**
00340yyyyyyyyyyyyyyy (barcode)
[Link](https://www.dhl.de/de/privatkunden/dhl-sendungsverfolgung.html?piececode=)

**DHL-parcel from DE to other country**
RM  yyy yyy yyy  DE (barcode)
[Link](https://www.dhl.de/de/privatkunden/dhl-sendungsverfolgung.html?piececode=RM662372122DE)

**DHL parcel from NL to DE**
JVGLyyyyyyyyyyyyyyyyyyyy


[Prüfziffern-Berechnung für Paketnummern](https://www.paketda.de/firmenkunden/paket-pruefziffern.html)

**Comment by Zahnstocher** [comment]
> And do you have a clue, how the last 4 bits are calculated (is it a checksum)?

It is CRC-4 with polynomial x⁴ + x + 1.

**Comment by Zahnstocher** [comment]
> ```            
> 44 45 41 35 00 01 35 0A C3 83 C2 A4 01 00 00 C2 B5 0F 02 04 25 C2 94 33 C2 87 27 77 49 40 C2 BD C3 83 C3 B7 6F 70 4D C2 AB 2B 3F 43 28 C2 AD 73 47 2D 00 50 00 00 00 00 00
>                                  A4 01 00 00    B5
>              0 01 35 0A C3
>                           C
> ```
> 
> The last one looks somehow different.

matrix code 44 45 41 35 ...
Byte 1 and 2 ist the country code "DE" (ASCII).
Byte 3 is the company "A" = "Deutsche Post" (ASCII).
Byte 4 is the type of franking, 35 means "stamp".

tracking number:
aaaaaaaaaa | bbbbbbbbb | c

aaaaaaaaaa contains information about the motif and some other things, always 10 HEX.
bbbbbbbbb is the "laufende Nummmer", always 9 HEX.
c ist the CRC-4.

@white-gecko 
A4010000B5001350AC3C was generated by the Post & DHL app?

https://www.deutschepost.de/de/s/sendungsverfolgung/verfolgen.html?piececode=A4010000B5001350AC3C

I had the same problem, the matrix code of a stamp had two **C2** in the "laufende Nummer", that I had to **remove** to get the valid ID (shown by Post & DHL app and accepted by the website).

**Comment by white-gecko** [comment]
Exactly, I have derived the tracking codes from the Post & DHL app.

**Comment by white-gecko** [comment]
Here are further codes:

```
444541350009F9F9D8A40100016A43010225E9FC94FBD9483FCBEFC282C593AEAE79D9958923835500A00000000000
                  A40100016A
         009F9F9D8
                  0


444541350005CDA12CA4010000B50F01062594338727774940BDC3F76F704DAB2B3F61BAEE3C472D00500000000000
                  A4010000B5
         005CDA12C
                  9


4445413500127AC2A96EC2A40100012D4A020A25C3A5561DC383212AC2BE267E2CC3AF3CC2A80710C2A15D30225AC2835500050000000000
                      A40100012D
         0127A  A96E
                    E
```

Also in this case we have an example with a overall bigger size and a `C2` in it.

**Comment by white-gecko** [comment]
@Zahnstocher I have tried to reproduce the CRC-4 with a random python library that I have found, but was not able to. Could you point me to some implementation and MWE (any language) that worked for you.

**Comment by Zahnstocher** [comment]
@white-gecko

1x^4 + 0x^3 + 0x^2 + 1x + 1 => 10011, first 1 is cut off, because it is contained in the specified order (4) => 11 => 0x3

Online:
http://zorc.breitbandkatze.de/crc.html

CRC order: 4
CRC polynom: 3
Initial value: 0
Final XOR value: 0
reverse data bytes: OFF
reverse CRC result before Final XOR : OFF

Data sequence: A4010000B5001350AC3
Result should be C.

MWE:

```c
#include <string.h>
#include <stdio.h>

const int order = 4;
const unsigned long polynom = 0x3;

const unsigned char string[] = {"A4010000B5001350AC3"};

unsigned long crcmask;
unsigned long crchighbit;

unsigned long crcbitbybitfast(unsigned char* p, unsigned long len) {

	unsigned long i, j, c, bit;
	unsigned long crc = 0;

	for (i=0; i<len; i++) {
		c = (unsigned long)*p++;

		for (j=0x80; j; j>>=1) {
			bit = crc & crchighbit;
			crc<<= 1;
			if (c & j) bit^= crchighbit;
			if (bit) crc^= polynom;
		}
	}

	crc&= crcmask;

	return(crc);
}


int main() {
	crcmask = ((((unsigned long)1<<(order-1))-1)<<1)|1;
	crchighbit = (unsigned long)1<<(order-1);

	printf("data string: '%s' (%lu bytes)\n", string, strlen(string));
	printf("Result: 0x%lX\n", crcbitbybitfast((unsigned char *)string, strlen(string)));

	return(0);
}
```

Derived from http://zorc.breitbandkatze.de/crctester.c

**Comment by Zahnstocher** [comment]
@white-gecko 

A 16 x 48 data matrix could not contain more than 47 Bytes of data, the remaining data is for error correction.
But your first "C2" stamp has 57 Bytes, the second one 56.
So I checked where the error is:
The text is interpreted as UTF-8, but it should be ISO 8859-1.
https://en.wikipedia.org/wiki/ISO/IEC_8859-1#Code_page_layout

The C2, C3, ... are UTF-8.
https://www.charset.org/utf-8

For example (from your stamps):
µ:
C2 B5 in UTF-8
B5 in ISO 8859-1

©:
C2 A9  in UTF-8
A9 in ISO 8859-1

Data transformed to ISO 8859-1, now the size is 47 Byte as expected and decoding looks good:

 ```
44 45 41 35 00 12 7A A9 6E A4 01 00 01 2D 4A 02 0A 25 E5 56 1D C3 21 2A BE 26 7E 2C EF 3C A8 07 10 A1 5D 30 22 5A 83 55 00 05 00 00 00 00 00 
                           A4 01 00 01 2D
             0 12 7A A9 6E
                          E

44 45 41 35 00 01 35 0A C3 A4 01 00 00 B5 0F 02 04 25 94 33 87 27 77 49 40 BD C3 F7 6F 70 4D AB 2B 3F 43 28 AD 73 47 2D 00 50 00 00 00 00 00
                           A4 01 00 00 B5
             0 01 35 0A C3
                          C
 ```

Uncorrected data of your stamps:

> ```     
> 44 45 41 35 00 01 35 0A C3 83 C2 A4 01 00 00 C2 B5 0F 02 04 25 C2 94 33 C2 87 27 77 49 40 C2 BD C3 83 C3 B7 6F 70 4D C2 AB 2B 3F 43 28 C2 AD 73 47 2D 00 50 00 00 00 00 00
>                                  A4 01 00 00    B5
>              0 01 35 0A C3
>                           C
> ```
> 
> The last one looks somehow different.


> ```
> 4445413500127AC2A96EC2A40100012D4A020A25C3A5561DC383212AC2BE267E2CC3AF3CC2A80710C2A15D30225AC2835500050000000000
>                       A40100012D
>          0127A  A96E
>                     E
> ```
> 
> Also in this case we have an example with a overall bigger size and a `C2` in it.

**Comment by white-gecko** [comment]
cool.
So is this an issue of BinaryEye to read the data matrix at utf-8, not iso 8859-1?

**Comment by Zahnstocher** [comment]
> cool. So is this an issue of BinaryEye to read the data matrix at utf-8, not iso 8859-1?

Short answer:
Yes, it is a BinaryEye bug (use of "text"), but it is not easy to fix it, because ZXing has a bug in "rawBytes" (which should be used here).

Long answer:
If raw data is needed, for example for hex view or further processing for tracking code calculation, com.google.zxing.Result.rawBytes should be used. If com.google.zxing.Result.text is used, there will be UTF-8 bytes added to the raw data in many cases, this isn't a ZXing bug.
But if the data matrix contains base-256 encoded segments, as this is the case for some stamps, com.google.zxing.Result.rawBytes returns ASCII + 1 (instead of ASCII) values for these segments, this is a ZXing bug. com.google.zxing.Result.text doesn't have this bug, but it has the UTF-8 problem.

**Comment by markusfisch** [comment]
Thanks to @Zahnstocher, it's now in version 1.51.0! 😄
