### ISSUE TITLE
Feature request: books/isbn only mode

### ISSUE THREAD

**Issue by RayBB** [markusfisch/BinaryEye#196]
Hey there thanks for making this awesome app!

I was wondering if it would be possible to add an option so that only isbns are detected. I've been using your book in bulk mode to scan sets of books in my house and then add them to openlibrary.org one thing that's been a mild pain is the barcode scanner tends to be a bit too good and sometimes recognizes things as barcodes that are not.

Anyway, if there was a way that it could only check for isbn10/13 that would be cool. It could even be possible to use a checksum for extra confidence. https://www.oreilly.com/library/view/regular-expressions-cookbook/9781449327453/ch04s13.html

Anyway, just an idea but I'm doing just fine with the program as it is now.

Cheers

**Comment by markusfisch** [comment]
Hi, and thanks for using it! Always glad to learn it's useful 😄 

Actually, the option to restrict scanning to certain types of barcodes is already planned for the next update!

**Comment by markusfisch** [comment]
Implemented in https://github.com/markusfisch/BinaryEye/commit/67395a067d5117ecd9b8af4501794c3263341bad

Will be in 1.44.0 which will become available shortly.

**Comment by RayBB** [comment]
Well hey it works well! Would be cool if you could indicate somehow that EAN-13 is the one most commonly used for books but loving it so far!
