### ISSUE TITLE
Crashes when opening the history

### ISSUE THREAD

**Issue by markozajc** [markusfisch/BinaryEye#20]
**App version:** 1.4.2

**Steps to reproduce:**
1. Enable history
2. Scan a QR code
3. (Attempt to) open the history

**Exception (from logcat):**
java.lang.IllegalStateException: Circular dependencies cannot exist in RelativeLayout

**Android version:** 7.0 (stock ROM, OTA upgrade from 6.0)

**Device manufacturer:** Sony

**Comment by markusfisch** [comment]
Oh - sorry for that and thanks a lot for reporting!

Fixed in 1.4.3.
