### ISSUE TITLE
Feature Request: Return to scanner when re-opening app

### ISSUE THREAD

**Issue by campbellkerr** [markusfisch/BinaryEye#206]
Currently we need to do a lot of scanning (for checking in to shops etc).

I would like BinaryEye to "reset" to the QR scanner (camera) every time I open/re-open it. Currently it opens at the last page (usually last scan result). This will make it a bit quicker to scan in to multiple places.

Normally, I scan a QR code, open the link (to check in). A few minutes later, when I re-open the app to scan another QR code, I have to tap BACK 🔙 to show the scan interface again.

Perhaps a timeout (eg 10 seconds) would be useful where if you haven't done anything with the scan result, it returns to the scanning screen?

Thanks!

**Comment by markusfisch** [comment]
Well, there are two options already:

First you could use the scanner in burst mode by checking the menu item "Scan continously" from the menu in the upper right corner (the three vertical dots). In this mode, the app will keep scanning after detecting a barcode (and possibly filing it in the history listing if you have this enabled).

The second option is to use the app shortcut for scanning, if your launcher does support app shortcuts. You can long press the app icon (of Binary Eye) to see if a list of additional app icons opens. You can drag those on your desktop an start the corresponding activity directly.

I hope one of these options work for you. If not please let me know 😉

**Comment by campbellkerr** [comment]
Thanks for the reply. 

I just tried "Scan Continuously" which does successfully identify the URL (toasts on the screen briefly), however it doesn't give me any option to open the URL 🤷‍♂️

My launcher does support shortcuts - however I launch from the lock screen using Notification Shortcuts (which doesn't appear to support app shortcuts) - not your problem to solve there.

**Comment by campbellkerr** [comment]
Yep, you can close this issue, the setting means I can scan in by opening the app without having to tap "back". Legendary!
