### ISSUE TITLE
Delay for continuous code reading

### ISSUE THREAD

**Issue by Natalia-Oreiro** [markusfisch/BinaryEye#208]
Hi, It would be possible to add a function for (Delay for continuous code reading) in milliseconds.

thanks.

**Comment by markusfisch** [comment]
You mean making the delay a preference? Yes, this is perfectly possible. Will add it in the next release.

**Comment by Natalia-Oreiro** [comment]
Yes, exactly

**Comment by markusfisch** [comment]
Implemented in https://github.com/markusfisch/BinaryEye/commit/8ecd49731fc74c9c9048a696fca7a1426a98c2df

Version 1.45.0 which will be available shortly.
