### ISSUE TITLE
Reset to homescreen when app was closed.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [markusfisch/BinaryEye#215]
I like the fact that the app stays on the URL-screen after a code was scanned.
However, when the application is closed, the user is done with whatever has happened.
Thus, I suggest displaying the homescreen on the next app-start.

**Comment by markusfisch** [comment]
Well, what do you mean by "when the application is closed"? When you leave the app by pressing the home button?

And how do you come back to the result screen?

**Comment by Glitchy-Tozier** [comment]
Turns out I didn't double-check properly. What I wanted to propose already existed within the app.

Closing the issue 🙈

**Comment by markusfisch** [comment]
No problem 😉
