### ISSUE TITLE
Remove unnecessary permissions from Android Q

### ISSUE THREAD

**Issue by ZBE69** [markusfisch/BinaryEye#216]
Hello,

As per [PRIVACY.md](https://github.com/markusfisch/BinaryEye/blob/af70d9507ba19739064949dd089de9b7112bf255/PRIVACY.md), the following permissions are unused in Android Q and above:
- **ACCESS_FINE_LOCATION**
- **WRITE_EXTERNAL_STORAGE**
- **ACCESS_WIFI_STATE**

Kindly consider removing them using the `android:maxSdkVersion` attribute. It should be backwards compatible till Android 4.4. Thank you.

Reference:
[uses-permission](https://developer.android.com/guide/topics/manifest/uses-permission-element)

**Comment by markusfisch** [comment]
Thanks for pointing this out 👍 

Implemented in https://github.com/markusfisch/BinaryEye/commit/4d38da045ab27c8dfb2423105933fe035bea160d
