### ISSUE TITLE
Intuitive logo

### ISSUE THREAD

**Issue by Ygarr** [markusfisch/BinaryEye#239]
May be can be useful also alternative logo
[logo2.svg.zip](https://github.com/markusfisch/BinaryEye/files/7696464/logo2.svg.zip)
![logo2021-12-11_07-05](https://user-images.githubusercontent.com/14309871/145664667-cf325bbc-8522-45b0-8a03-f16a2ed0b925.png)

**Comment by Glitchy-Tozier** [comment]
As there's a new logo, this possiblycould be closed.
@markusfisch

**Comment by markusfisch** [comment]
Yes, that's right.

@Ygarr Nevertheless, thank you for your contribution.
