### ISSUE TITLE
Pr?

### ISSUE THREAD

**Issue by realrufans** [markusfisch/BinaryEye#24]
Hello, I'm back again. it's my first time trying to contribute via PR. is it welcomed? 😊

**Comment by realrufans** [comment]
BinaryEye is in Kotlin 🤔 I thought Is Java. My codes are in Java 🤦‍♀️

**Comment by markusfisch** [comment]
Yes, contributions are very welcome!

And don't be afraid of Kotlin. If you know Java, it won't be a problem. It's not that different and online documentation is great (have a look at https://play.kotlinlang.org/koans/overview). I promise it will be worth your time 😉
