### ISSUE TITLE
(U.I.) Zoom Bar goes away after switching cameras.

### ISSUE THREAD

**Issue by Mario675** [markusfisch/BinaryEye#241]
## Thanks:
Thanks to all contributors for this app. It's greatly convenient, and the history feature is a great addition. Moving unto the issue. Thanks to any participants who join in on the issue. 

### Description: 
This can be reproduced by switching cameras. The Zoom bar disappears after switching cameras. Switching back to the main camera will not make the zoom bar re-appear. Zooming still works by touch in the main camera (zooming in the front camera doesn't seem to be supported by all other camera apps I have).

#### Speculation
- The app might have turned off the zoom bar due to the front camera not supporting it, but doesn't turn back on when it switches back to the main camera.

#### Priority

I consider this a minor priority ui bug. I wouldn't lose sleep over this.

### Workaround
Kill the app, restart it, don't switch cameras.

### App version:
- 1.46.3, according to f-droid.
  
### OS used
  - I use a Galaxy S4 with linage os on it. It has android 11.
  #### Os Version
  - LineageOS 18.1
  #### Build number:
lineage_jfltexx-userdebug 11 RQ3A.211001.001 10037649

**Comment by markusfisch** [comment]
Good catch! And thanks a lot for filing an issue 👍 

This was a bug and it's now fixed in https://github.com/markusfisch/BinaryEye/commit/95d7a84648365b4044b53401634fc5bf6e10b658

Thanks for reporting!
