### ISSUE TITLE
Not usable after updating to 1.48.0

### ISSUE THREAD

**Issue by JokerQyou** [markusfisch/BinaryEye#248]
BinaryEye was updated to 1.48.0 via Google Play, and after the update it's not usable for me, here's the detail:

- If I scan a QR code containing a URL, the text content only shows alphabet characters and numbers, the `://` and `/` are replaced with `...`. I assume it's due to 315abfb1dda8c8173de617bf0cd70325a804bb2f, although I don't understand the intention of this commit. But the hex preview does decode the text into a URL correctly.
- There's not copy button. Before the update, there is a "copy" button as well as "share" and "compose" buttons on the top right side of the scan result. Now there's only a share button, so I've got no way to copy the scanned URL.
- When clicking the "open URL" button on the bottom right of the scan result, it does not open the URL in browser, but prompt for a filename via dialog. It seems like BinaryEye would try to save the content as file.
- I tried to share the scan result to other apps to get its content, but the shared content seems to be the original hex text rather than the actual URL.

Attached the screenshot of a sample scan result:

![image](https://user-images.githubusercontent.com/1465267/157869942-63fc8154-1864-4bb6-b190-f9062a141332.png)

**Comment by markusfisch** [comment]
Sorry for this bug and the inconvenience 🙈 I will fix this asap!

**Comment by markusfisch** [comment]
Fixed in https://github.com/markusfisch/BinaryEye/commit/b895997967cd2aa959d71932c48522a57e6c6119

Version 1.48.1 is on Google Play and should become available within the next few hours.

You may also update directly from GitHub:
https://github.com/markusfisch/BinaryEye/releases/tag/1.48.1

Thanks again for reporting this bug! 👍 And again, sorry for the trouble 🙈
