### ISSUE TITLE
Can't copy content anymore since 11. march update (1.48.1) - seems like everything is detected as binary data now

### ISSUE THREAD

**Issue by najtin** [markusfisch/BinaryEye#249]
Hi, awesome app. Really, thank you so much. 
There is a problem with the latest update (11. march 2022, version 1.48.1). I think i remember that it was possible to copy data from the decoded field. Any qr code seems to be registered as binary data. I can not copy the decoded content. If i press the share button, then the byte values get shared.
Also `:` and `/` are decoded as `.`.
![Screenshot_20220313-153855](https://user-images.githubusercontent.com/42641080/158065186-227c739c-ccf2-42f0-a661-0eed421398f4.png)

**Comment by markusfisch** [comment]
Yes, sorry, this is a bug in version 1.48.0 😬🙈 But it's already fixed in version 1.48.1 which should also be available on Google Play right now. If you don't see 1.48.1 yet, you can also update directly from GitHub here:
https://github.com/markusfisch/BinaryEye/releases/tag/1.48.1

Again, sorry for this inconvenience.

**Comment by najtin** [comment]
Ah, sorry i should have included that in the first message. I am on 1.48.1.

**Comment by markusfisch** [comment]
Oh 😳 Sorry, that's really strange!

I just made a QR Code like you scanned it and I can't reproduce the bug 😬 Does it work when you scan this code?
![image](https://user-images.githubusercontent.com/485246/158133733-c8aa28d6-5373-4584-a187-a99942e00254.png)

If it works, would it be possible to share the sample QR Code that doesn't work so I can see what's going wrong?

**Comment by najtin** [comment]
Okay, i cant reproduce it either now. Maybe i got the update over night and remembered incorrectly about the version. Thank you very much. Since the issue seems to be resolved, i will close this. Thanks again. Thank you.

**Comment by najtin** [comment]
And sorry for the fuss.

**Comment by markusfisch** [comment]
No problem, glad it's working now 😄 

And thanks for reporting anyway! I'm always happy to get feedback when something isn't working as it should.
