### ISSUE TITLE
Does not reconize extended EAN13 barcodes

### ISSUE THREAD

**Issue by the-Arioch** [markusfisch/BinaryEye#25]
Barcode picture example : 
https://stackoverflow.com/questions/40847508/possibility-for-ean135-addon-barcode-scanning-in-ios

zxing library seems to have this opption (not application though, but they said their application is dead anyway): https://stackoverflow.com/questions/40847508/possibility-for-ean135-addon-barcode-scanning-in-ios

**Comment by realrufans** [comment]
I was about to read the first barcode from that post.

**Comment by markusfisch** [comment]
Unfortunately, I don't think ZXing supports EAN_13+5. There's EAN_13 only:
https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/BarcodeFormat.java

**Comment by realrufans** [comment]
I was able to read the first code in that post tho.

**Comment by markusfisch** [comment]
Yes, the code on the left is a valid EAN13 indeed. ZXing, and therefore Binary Eye, can read it. But ZXing doesn't do anything with the accompanying second part on the right what's the `+5` thing.
