### ISSUE TITLE
Feature Request - Toggle for Send every scan to URL

### ISSUE THREAD

**Issue by Vongalin** [markusfisch/BinaryEye#251]
Hello ! Thank you very much for this wonderful app. I have started using it recently to test the "Send every scan to URL" option and it functions perfectly. The problem is, I don't always want it to do this as I scan other entries. The only way I have found to disable this option is to blank out my custom URL (unless I am missing some other setting).
Is it possible to add a toggle option to the Forwarding section ? This way, if on, it would send to the configured URL and if off, just a normal scan.

Thank you.

**Comment by markusfisch** [comment]
Yes, such a toggle makes totally sense! Good idea 👍  

Expect this to be in the next update.

**Comment by markusfisch** [comment]
Implemented in https://github.com/markusfisch/BinaryEye/commit/197554fd1bb8d1e1742e178324ef9185cbed21be
