### ISSUE TITLE
The application produces sounds when the phone is in silent mode

### ISSUE THREAD

**Issue by rbsamoht** [markusfisch/BinaryEye#252]
## Environment
**BinaryEye Version:** 1.48.1
**Android Version:** Android 11

## Issue description
The application produces three audible beeps when the phone is in *Silent mode* and *Ring & notification volume* is set to 0.
Maybe a new opt-in setting could be introduced to enable this behavior (produce a sound in silent mode) ?

## Steps to reproduce
- Set the Android phone in silent mode
- Set Ring & notification volume to 0
- Open Binary Eye
- Go to preferences
- Set some non working URL under the **Forwarding** -> **Send every scan to URL** setting
- Scan a barcode
- Wait a few seconds, until the Forwarding request fails

## Expected Behavior
The application should only display the Toast Message presenting the failure, without producing any sound (since the phone is in Silent mode and Ring & notification volume is set to 0)

## Actual Behavior
The application displays the Toast message and produces three short sounds

**Comment by markusfisch** [comment]
Fixed in https://github.com/markusfisch/BinaryEye/commit/3dc35ac60d2be057209b4ce06f0142598343346c

Thanks for posting such a detailed error description 👍 Much appreciated! And thank you for contributing! 😄
