### ISSUE TITLE
BinaryEye not in official google android play store any more? url not found on this server

### ISSUE THREAD

**Issue by subscribernamegoeshere** [markusfisch/BinaryEye#257]
Just tried to fetch this nice app on some nonpopulated new other different android smartphone just recently and google place store webpage gives me the url not found on this server and manually searching for string: binary eye  doesnt come up with the results to this app either.

on some older phone the binary eye app is happily installed but i can not go to play store any more and see its app details any more there either.

are you booted off from play store or anything suspicious happening? binary eye banned by google?

also on classic desktop browsers visting that icon from play store also given here on the github project page doesnt yield in proper result but gives the error page not found details not found

tried this link
https://play.google.com/store/apps/details?id=de.markusfisch.android.binaryeye

anyone? issue and situation known to you guys? anyone gonna reclaim the stuff in google play store? thanks.

**Comment by markusfisch** [comment]
I think it's back! 😄 

https://play.google.com/store/apps/details?id=de.markusfisch.android.binaryeye

**Comment by subscribernamegoeshere** [comment]
yes thank you, thanks lots, the app returned to the google play store already. thanks again. well done. good job. thanks for the app.

**Comment by moriel5** [comment]
I personally prefer the old icon, but whatever works.

But yeah, Google's automated system is so unstable, that it's a wonder that businesses don't just band up and outright boycott the Play Store (probably due to Google's illegal terms of use, and how people forget that the Play Store is far from the only way to distribute apps as a result of that).
No wonder your app was flagged, when apps are regularly flagged for absolutely no reason whatsoever, and no one at Google's management team cares about it.

**Comment by ddarfantasy** [comment]
The current new icon is so ugly and awful... I can hardly think it's bearable.
A suggestion: make the black eye solid again, and make a smaller grey barcode inside the eye. It will certainly be more acceptable than the current one.

**Comment by moriel5** [comment]
> The current new icon is so ugly and awful... I can hardly think it's bearable. A suggestion: make the black eye solid again, and make a smaller grey barcode inside the eye. It will certainly be more acceptable than the current one.

While I also prefer the old icon, this is not so bad, the eye was simply replaced with barcode, after all.
