### ISSUE TITLE
App fails to recognize URLs that don't start with http or https

### ISSUE THREAD

**Issue by EmilJunker** [markusfisch/BinaryEye#263]
When I scan a QR code that contains the text "www.example.com" like this one...

![qr-code](https://user-images.githubusercontent.com/19289477/166111944-ec4c149a-1149-4f1f-a117-d0c2c4d850d8.png)

... I would expect the app to recognize that this is a URL and offer me to open it in the browser. But instead, it only lets me search for it in online search engines.

The same is true (but that's arguably trickier) for URLs that don't even have the www prefix:

- example.com
- foo.example.org
- example.co.uk
- example.fr

**Comment by markusfisch** [comment]
Well, technically it's not a URL (that can be opened by a web browser) if there's no `http(s)` scheme 😬

But I know it's quite common to drop the scheme, of course. So I'll try to find a better way to recognize these strings as (http) URLs too.

It's just not that trivial (or clear) to recognise these strings as URLs, I'm afraid. Either there will still be samples that aren't recognized, or there will be false positives. For example, is "this.that" a URL? 🤔

**Comment by EmilJunker** [comment]
It would already be an improvement if the app could at least recognize URLs that start with www.

But I think it should also be possible to recognize other URLs. Having false positives is not a problem in my opinion. It the app is unsure whether the encoded text is a URL or not (but there is a possibility that it might be, e.g. "this.that"), then it could simply display the text as it normally would, but offer an _option_ to open it in the browser.

**Comment by markusfisch** [comment]
Implemented in https://github.com/markusfisch/BinaryEye/commit/6852b6523960762c9ebb283759cad93f5b97eb10

Will be in the next release.
