### ISSUE TITLE
MATMSG e-mails are processed as text instead of e-mail

### ISSUE THREAD

**Issue by travelalpaca** [markusfisch/BinaryEye#265]
BinaryEye correctly handles mailto format as e-mail, but it fails to handle MATMSG format as e-mail.

Example of mailto format from [here](https://qrcode-library.readthedocs.io/en/latest/formats/mail-to/):

> `mailto:hola@2amigos.us`

Example of MATMSG format from [here](https://qrcode-library.readthedocs.io/en/latest/formats/mail-message/):

> `MATMSG:TO:support@morovia.com;SUB:QRCode Generator;BODY:you guys are doing a great job!;;`

Other resources on MATMSG:

- https://www.openmobilealliance.org/release/MobileCodes/V1_0-20081024-A/OMA-WP-MobileCodes-20081024-A.pdf (OMA-WP-MobileCodes-20081024-A, see 6.2.2.1)
- https://gist.github.com/arvati/1b834f7c0f67199d8b25d5e2820a197a see E-mail address section note on MATMSG which links to...
- https://web.archive.org/web/20130330190304/http://www.nttdocomo.co.jp:80/english/service/developer/make/content/barcode/function/application/mail/

**Comment by markusfisch** [comment]
Yes, unfortunately, MATMSG isn't supported yet. Thanks for pointing this out! 👍 Somehow I haven't come into contact with it yet.

I will add support for MATMSG with the next release.

**Comment by markusfisch** [comment]
Implemented in https://github.com/markusfisch/BinaryEye/commit/57fea95b9b6e9092b74da1aba15e682a535e843d

**Comment by travelalpaca** [comment]
I see that this was implemented in Version 1.50.0, however I don't think it's working correctly.
I am testing the MATMSG example, and while Binary Eye now does call up the e-mail app, it doesn't fill out all the fields correctly.  I tested on a couple devices and a couple e-mail apps, and in no case was the To address filled out, and it was inconsistent whether the Subject or Body was filled out.

I also tested the ZXing scanner https://f-droid.org/en/packages/com.google.zxing.client.android/ and it successfully handles MATMSG in all the cases I tested.

**Comment by markusfisch** [comment]
You're right, sorry! The `TO:` address was incorrectly transferred. Fixed in [75a59b](https://github.com/markusfisch/BinaryEye/commit/75a59bc3e98220ecac476cf5be715870fdc2b828)

But I don't understand why Subject or Body isn't reliably filled out 🤔 Can it be that `SUB:`/`BODY:` isn't all upper-case in some of these samples? Or is `MATMSG:` missing?

Would you mind sharing some of the samples that do not work?
