### ISSUE TITLE
Cannot scan codes that span through whole image

### ISSUE THREAD

**Issue by ss11mik** [markusfisch/BinaryEye#268]
When scanning code from loaded image, the scanning area stays in the middle. This is not much of an issue when scanning with camera, since user can move a little backwards. But when user selects an image where the margins are not big enough (thinking mostly of generated images of QR codes, not photos of them), BinaryEye simple cannot detect it.

So the app should be able to unzoom beyond images bounds.

Simple example: generate QR code with the app (with any content and resolution, I used "hello" and 1024*1024) and save it as png. Then open it in the app and try to detect the QR code.

**Comment by markusfisch** [comment]
Well, the simple example is working for me 🤔 

https://user-images.githubusercontent.com/485246/168423723-667b8921-4cd8-4138-a685-cc7b3f2ba899.mp4

Did you miss that the cropping window can be modified and even be removed?

**Comment by ss11mik** [comment]
You're right, its working :smile: 
There must have been some inconsistency, the cropping window was disabled in settings, but visible in the scan and it didn't have the handle.
After switching the option on and off, I can't even get it back to that state, so it must have been a weird rare bug. It was like that for a few months (and app versions) on my phone, but I can't reproduce it or tell you more details, so consider it closed. :smile:

**Comment by markusfisch** [comment]
Ah, okay, I see 😉 But you still found a bug then! 🙈

I will check if I can find and fix this inconsistency bug. If it happens again, please don't hesitate to report it here. Feedback is always welcome! 👍
