### ISSUE TITLE
Scan history - share the whole list instead of specific items

### ISSUE THREAD

**Issue by gradinaruvasile** [markusfisch/BinaryEye#27]
Right now only specific history items can be shared.
It would be good to have an option to share the whole history as a list too.

BTW the app is very good. Light, fast, has all the features it needs (besides sharing the whole history list :) )

**Comment by markusfisch** [comment]
Good idea! Would it be okay to share it as plain text or were you thinking about a specific format?

**Comment by gradinaruvasile** [comment]
Plain text is fine, it can be used in any app. Only make sure that they
contain line breaks.

**Comment by markusfisch** [comment]
Implemented in https://github.com/markusfisch/BinaryEye/commit/a21bfcdea6859a52001497e3bb41c40543807851 and available from 1.6.0 currently in Beta:

https://play.google.com/apps/testing/de.markusfisch.android.binaryeye

Or directly from GitHub:
https://github.com/markusfisch/BinaryEye/releases/tag/1.6.0

**Comment by gradinaruvasile** [comment]
The implementation works but it also exports timestamps and some delimiters.
The typical use case for this function would be to scan a number of codes then transfer it to another app or list where these codes would be used for something. The timestamps and delimiters have no relevant data on them and filtering them out would involve extra post processing.
Can this be implemented to export only the effective data, the barcodes only?

**Comment by markusfisch** [comment]
Removing the timestamps would be no problem. I've just included them so the export contains all of the data there is.

For the delimiters, it's different. You see, many barcodes may contain line breaks. Without the delimiter, there would be no way to tell the entries apart.

Well, I think it's quite obvious that a simple generic export isn't sufficient. There should be a dialog asking for export options. Or maybe add a settings screen.

**Comment by gradinaruvasile** [comment]
I personally did not use barcodes with newline characters, but you are
probably right especially if one has QR codes.

My idea was based on the usual plain codes where you have  some products
that have a single string that defines the serial number or type.
I don't think anyone would put multi line barcodes in these cases because
it would mess up processing. For the purpose of this app, this shoould be
the main focus since multi line barcodes are not typically used in cases
where you really need batch processing.
For starters, removing the timestamps would be good and probably easiest.
Maybe remove the delimiters too then treat the non standard barcodes later
with an option to set delimiters for batch export. Or add delimiters only
for the non standard codes that have newlines inside them.

**Comment by markusfisch** [comment]
I see. So I've added a simple dialog asking what kind of separator you want to have when you export a listing.

It's in 1.7.0 that's currently in beta if you want to check it out:
https://play.google.com/apps/testing/de.markusfisch.android.binaryeye

**Comment by gradinaruvasile** [comment]
Tested it and seems to work fine. Thanks.

👍👍👍
