### ISSUE TITLE
Scanner as Keyboard

### ISSUE THREAD

**Issue by thejeshgn** [markusfisch/BinaryEye#273]
I am not sure what it takes. But if there was a way to trigger the scanner from keyboard and post scan the content goes back to the text box or editor, it would be easy to scan things as part of a form.

**Comment by thejeshgn** [comment]
Ah this app seems to have a similar functionality

https://play.google.com/store/apps/details?id=com.tecit.android.barcodekbd.demo

Or at least tells you what I mean.

**Comment by BobSynfig** [comment]
The thing is that it has to be taken as the reverse.
This is a keyboard application which has to implement the scan functionnallity (at least a call to an intent).
Maybe BinaryEye could offer in the future the implementation of an open-source keyboard (some can be found on F-Droid) ;)

**Comment by markusfisch** [comment]
Well, I see why it would be handy, but adding a keyboard just to add this functionality seems way beyond the scope of this app 😬 If it was possible to add this to existing keyboard applications, I would definitely want this. But doing a whole keyboard just to have that button is just overkill in my opinion 😉 

But the app already offers a Quick Settings Tile as well as a launcher shortcut to open the scanner quickly. Once something is scanned, it's easy to copy and paste it. I realize this takes a couple of taps more than having it right in the keyboard, but I guess this use case is too rare to justify the weight and complexity a keyboard implementation would mean.

That said, there _may_ be already some keyboard applications that allow adding custom buttons for Intents 🤔 If so, it would be really easy to invoke Binary Eye from there with a [SCAN Intent](https://github.com/markusfisch/BinaryEye#scan-intent).
