### ISSUE TITLE
raw data in JSON export message is based on wrong charset, unprintable characters are translated to placeholder

### ISSUE THREAD

**Issue by EdwinHoogland** [markusfisch/BinaryEye#276]
The raw data in JSON export message is based on wrong charset, unprintable characters are translated to placeholder

when sending scanned data to a url, the raw data is sent as hexstring

when the barcode data is in binary (like in UIC barcodes) the unprintable characters are translated to Ã or some other character placeholder, this corrupts the data.

It looks like that all data is translated to string, and that string is translated to hexstring.  it should be from binary to hexstring.

corrupt data : 
#UT010087000010,-û:IÜ¯E`rhTì5ïX@¯@,
c

**Comment by EdwinHoogland** [comment]
sure :)
I scanned a db UIC specimen barcode, and I received in the json message this string:
235554303231303830545432303252C2B9C29101734D6226C29E7E2FC29A591C65C2987736C3B1C380C293786B6AC2B2066C126AC2AAC29F7F67C2936A3368C3B005C3B539655A68C39D100D0AC2A9C380C2AF3D74C39E45C3AC540BC28EC2837DC28FC388483032353378C29C0BC28D77C3B371C28D30343630C2B4344CC39AC384C390C3B6C290C3B760C38772015141C28E4656C2B916C297C382C398C393C291C2856F15C2B81A1838C29AC3AEC39C39C38436C3ABC390654616C297703B4706C2A5C3A6C2B4C29E1B262B53C38C7C2C5628275E3C1D27176B34C2AF273D717E0EC28BC2A0C3817BC2993B37C2A325C2A5C3AFC38CC3ACC2BA702B56C38E79C382C29CC2B971C292C391C392C29231C2A7C283C2A322C2A5C2BCC2AFC38EC28AC3B0C3ABC3A0C3A7C3B1C3A1C3A3C3A1C3AF123A3549C3B8C38AC294C2AEC289C382C39DC297034F4DC299C3A6C3A53521C3A0C394C284C2802B174F4DC296C28AC28CC2BCC3A92136C3BBC3B64CC287030C0F587459581E345D4D64493B16C39EC38EC2AE1636C39DC288253C5CC3AD3BC29BC280C281C281C2854158C2A8C281C2A1C281C281C2A931030830323AC3B56DC397C2912861C2BF2051C3A650C386C380C3A0502E0112060972C39C61C3A3C29528C2AB120A05006AC28E57C290

but it should be:

235554303231303830545432303252b99101734d62269e7e2f9a591c65987736f1c093786b6ab2066c126aaa9f7f67936a3368f005f539655a68dd100d0aa9c0af3d74de45ec540b8e837d8fc84830323533789c0b8d77f3718d30343630b4344cdac4d0f690f760c7720151418e4656b91697c2d8d391856f15b81a18389aeedc39c436ebd065461697703b4706a5e6b49e1b262b53cc7c2c5628275e3c1d27176b34af273d717e0e8ba0c17b993b37a325a5efccecba702b56ce79c29cb97192d1d29231a783a322a5bcafce8af0ebe0e7f1e1e3e1ef123a3549f8ca94ae89c2dd97034f4d99e6e53521e0d484802b174f4d968a8cbce92136fbf64c87030c0f587459581e345d4d64493b16deceae1636dd88253c5ced3b9b808181854158a881a18181a931030830323af56dd7912861bf2051e650c6c0e0502e0112060972dc61e39528ab120a05006a8e5790.

some data is lost probably because of a conversion

<img width="413" alt="image" src="https://user-images.githubusercontent.com/18666574/173071505-c0050a57-d746-4854-b288-67efb977a4fa.png">

**Comment by markusfisch** [comment]
Fixed in https://github.com/markusfisch/BinaryEye/commit/60f0d8bd878720e1205d3e1118f6d408c82c72c1

Thank you for the sample and for taking the time to filing this issue 👍 

Version 1.51.1 with this fix should become available soon on Google Play:
https://github.com/markusfisch/BinaryEye/releases/tag/1.51.1
