### ISSUE TITLE
wrong time when importing events

### ISSUE THREAD

**Issue by dbloms** [markusfisch/BinaryEye#284]
I get my appointments via QR code in the local time zone.
If I accept the scanned qr code as an appointment, then it is two hours in the future.
Is it possible to take over the times directly, i.e. without considering the time zone.
I attached an example.  
Here the appointment at 09:00  
<img src="https://user-images.githubusercontent.com/14087328/183824498-f8aba6c5-7033-4d2a-bc74-f604e8ee155a.png" width="150">  
and when I add these event to calendar, it show 11:00 o'clock
<img src="https://user-images.githubusercontent.com/14087328/183824556-a5e254e6-182b-4b48-83dd-f209bd9c5f9d.png" width="150">

**Comment by markusfisch** [comment]
Ah, yes, sorry for the bug 😬  Right now any date without a time zone defaults to Zulu time, which explains the 2 hours offset.

Will fix it as soon as possible!

**Comment by markusfisch** [comment]
Fixed in https://github.com/markusfisch/BinaryEye/commit/3633af5e0aeee560c43031fa22d7a85a707b575a

Version 1.52.0 should become available shortly on Google Play and F-Droid.

You can also get it directly from GitHub:
https://github.com/markusfisch/BinaryEye/releases/tag/1.52.0
