### ISSUE TITLE
Multi-Select History Item for Bulk Operations

### ISSUE THREAD

**Issue by RuthlessRuler** [markusfisch/BinaryEye#285]
As stated, if I select an Item in history and then I tap another item, instead of selecting the item, the new item opens and it's content is shown instead of getting selected for bulk operations.

If we could allow for bulk selection of items to delete /copy then it would be great

**Comment by markusfisch** [comment]
Yes, I totally get why muti-select is desireable and I will add this feature in the future 👍 

In the meantime, I know it's not the same, but you can already (kind of) bulk select by using the search. The delete/share/export actions only apply to the current listing. Of course, that's only useful if the scans you want to group have some common content that is exclusive to them.

**Comment by markusfisch** [comment]
Implemented in https://github.com/markusfisch/BinaryEye/commit/bb4fc8ed08d25e18a895fbb7725b399d8446d8e1

Will be in the next release.
