### ISSUE TITLE
qr code version

### ISSUE THREAD

**Issue by bderembl** [markusfisch/BinaryEye#289]
This is not an issue but more a question (probably more related to zxing than binary eye):

I see [here](https://www.qrcode.com/en/about/version.html) that the size of the QR code is determined based on the length of the data:
version 1 should hold up to 17 binary characters. So "abcdefghijklmnopq" (low cap) should be in version 1 whereas "abcdefghijklmnopqr" should be in version 2. However, "abcdefghijklmnopq" is already in version 2 (and "abcdefghijklmnop" is in version 1).

I see that another QRcode app that also use zxing (https://github.com/wewewe718/QrAndBarcodeScanner) encodes "abcdefghijklmnopq" with version 1 and "abcdefghijklmnopqr" with version 2.

Also, with Binary eye, the transition from version 2 to version 3 is again shifted by 1 character.

My (silly) question is: why is there such a shift with binary eye?

Thank you

**Comment by markusfisch** [comment]
Good question 😉 I guess you encoded "abcdefghijklmnopq" with an error correction level > L (7%)

It's not a shift - it's the error correction level 😉 See, error correction works by adding redundant data so some of the data can be lost. 

If you encode "abcdefghijklmnopq" with Binary Eye and an error correction level of L (~7%), you will get version 1. You can verify this with Binary Eye when you enable "Show QR version" in the settings.

I guess you made your tests with an error correction level of M (~15%), which would add just enough extra data to require version 2.

**Comment by bderembl** [comment]
@markusfisch : thank you very much for your reply.
no, I really did it with level L. actually here are the QR codes I get:
https://zxing.org/w/chart?cht=qr&chs=350x350&chld=L&choe=UTF-8&chl=abcdefghijklmnop
https://zxing.org/w/chart?cht=qr&chs=350x350&chld=L&choe=UTF-8&chl=abcdefghijklmnopq
(these are exactly the same QR I get with binary eye)

To check the version number, I simply count the number of modules (21 for abcdefghijklmnop and 25 for abcdefghijklmnopq).

Again this is really not a binary eye issue but more zxing related. I simply don't understand the shift (and why the other app I mentioned above which also uses zxing does not have this issue).

**Comment by bderembl** [comment]
it seems that the character encoding makes a difference: here is the result with ISO-8859-1. There must be one necessary extra byte for UTF-8?

https://zxing.org/w/chart?cht=qr&chs=350x350&chld=L&choe=ISO-8859-1&chl=abcdefghijklmnopq
