### ISSUE TITLE
Unable to configure WPA2-EAP (Enterprise) WiFi

### ISSUE THREAD

**Issue by JacobKochems** [markusfisch/BinaryEye#293]
Hello, I installed the app version 1.52.0 within Android 12 and created a QR code with the following content:

`WIFI:T:WPA;S:test-ssid;P:secret;H:false;;`

which follows the very format the Android 12 WiFi settings page uses for sharing network credentials via QR code. When I scan it with Binary Eye the correct string gets displayed and the button to add a WiFi profile appears. After hitting that button a short message appears on screen telling me that it was unable to configure the WiFi.

I also tested it with:

`WIFI:T:WPA2-EAP;S:<my-ssid>;E:pwd;I:<username>;P:<password>;;`

and got the same result.

Thank you for your time.

**Comment by markusfisch** [comment]
Hello, and sorry for the long delay, and also for the inconvenience 😬 

Unfortunately, there can be many reasons for this 🙈 The WiFi string looks fine 🤔 Were Binary Eye able to add other networks before on your device?

**Comment by JacobKochems** [comment]
Hello, thanks for the response.
To your question: I used to be able to log into any WiFi (WPA/WPA2-EAP) as long as the QR code followed the string format from my original post minus the `H:false` flag which I just left out. What changed wasn't the WiFi network but I got a new phone. Before I still had an old Nexus5X with Android 8. Now I replaced that with a Zenfone9 with Android 12. My guess is, that something in the WiFi settings API in Android has changed.
The WiFi settings page on my new phone gives me the option to scan QR codes now. But that only works for simple home WPA networks with a passphrase and not with WPA2-EAP. That is why I used Binary Eye, because it could do just that. I use my own radius server at home to manage guest access.

**Comment by tu-maurice** [comment]
I seem to have experienced a similar problem with my Android 11 device. I added my company's Wifi via a QR code scanned through Binary Eye. I was able to connect without any issues. It said "Connected via Binary Eye" in the settings app next to the network.

However I was neither able to edit nor to delete the network neither through the settings app nor through Binary Eye. Ultimately I was able to get rid of it by uninstalling Binary Eye temporarily. 

My guess is the interface Binary Eye is using to add WiFi networks is meant for temporary network connections, e.g. a hotel app could connect a guest for the duration of their stay. Maybe there's a flag to not give a newly added WiFi network this special role?

**Comment by JacobKochems** [comment]
@markusfisch I did some more testing to get a clearer picture. I used a Debian laptop to create a WiFi hotspot and tested the following cases:
| QR-Code Reader | WiFi Config String<br>(encoded with 'qrencode') | Message | Behavior |
|:-----------------------|:------------------------------------------------------------------|:-------------|:------------|
| Android 12 native<br>(via WiFi Settings) | `WIFI:S:hotspot-ssid;T:WPA;P:invalid;;` | "Check connection<br>and try again" | nothing |
| Android 12 native<br>(via WiFi Settings) | `WIFI:S:hotspot-ssid;T:WPA;P:valid;;`    || Auto connect to hotspot.<br>Add to<br>'Saved networks'. |
| Binary Eye                                             | `WIFI:S:hotspot-ssid;T:WPA;P:invalid;;` | "Could not<br>configure WiFi" | nothing |
| Binary Eye                                             | `WIFI:S:hotspot-ssid;T:WPA;P:valid;;`    | "WiFi added" | No auto connect.<br>Add to<br>'Available via Binary Eye'.<br>Not visible if hotspot is off.<br>Not listed in<br>'Saved networks'. |

Apparently, I didn't thought off the possibility of failure to configure because of failure to connect when I created this bug report. I apologize for the confusion this might have caused.
I have to look at the `WPA2-EAP` case again. I could not test it right now. I will report on this case again when I managed to do so and maybe rename this issue accordingly.

@tu-maurice I had a look into Binary Eye's code and I found that since version 10 of Android (API level 29) the class `WifiConfiguration` is deprecated. See https://developer.android.com/reference/android/net/wifi/WifiConfiguration. From Android version 10 and upwards, Binary Eye uses `WifiNetworkSuggestion.Builder` to replace it. The behavior you described seems to be the intentional result. That is to say, that apps should no longer be able to save to the global android network config namespace. Instead it seems to be intended, that each app has its own network config namespace now. Apparently, a side effect of this is that a network configuration can only be added, even to its own namespace, if it is currently accessible.

**Comment by JacobKochems** [comment]
I had the opportunity to test the `WPA2-EAP` (WPA2-Enterprise) case with Binary Eye v1.56.3 last evening. It turns out, that the WiFi config string

`WIFI:T:WPA2-EAP;S:<my-ssid>;E:pwd;I:<username>;P:<password>;;`

of my original post, does **not** work and returns the "Could not configure WiFi" message. It took me some time and trail and error to find, that instead this config string

`WIFI:T:WPA2-EAP;S:<my-ssid>;E:PWD;I:<username>;P:<password>;;`

just works like expected.

Don't feel bad if you can't spot the difference right away. I overlooked it for quite some time but finally found it. The EAP-Method is specified wrong: `E:pwd`. Instead it should read: `E:PWD`. It has to be upper case for it to work. I was not expecting case sensitivity here.

Hopefully, this will help someone else having similar troubles.

Best Regards
Jacob

**Comment by markusfisch** [comment]
Ah! Thanks a lot for sharing and all the effort to find the problem! 👍 Good catch!

Debugging WiFi configurations is a really tedious and time consuming task so this is much appreciated!

To save others from this, I have made Binary Eye case insensitive for `E`, `PH` and `T` in https://github.com/markusfisch/BinaryEye/commit/e9267e4e5a0d04f4603a35dc3c90d432b5e92934

Although this might confuse people who use Binary Eye to check that the QR code they have just created works 😬 But following the [Robustness principle](https://en.wikipedia.org/wiki/Robustness_principle) it's probably still best to accept lower case values as well.

About removing/editing individual network suggestions (also discussed in https://github.com/markusfisch/BinaryEye/issues/197): unfortunately it's not possible to get a list of the suggestions an app has added before 🙈 There is just [getCallerConfiguredNetworks](https://developer.android.com/reference/android/net/wifi/WifiManager#getCallerConfiguredNetworks()) but that is only available from API level 31 on. So this might only be possible for newer devices.

**Comment by JacobKochems** [comment]
@markusfisch Would [this](https://github.com/markusfisch/BinaryEye/issues/197#issuecomment-1332169730) work maybe?
