### ISSUE TITLE
Long pressing the icon to "Create a barcode" issue 

### ISSUE THREAD

**Issue by Allbutnotnothing** [markusfisch/BinaryEye#299]
Long press the Binary Eye icon --> select Create a barcode
There is always the "encode" text in the Content field. So have to manually delete it before entering my content

**Comment by markusfisch** [comment]
Sorry, this was a bug indeed 🙈 

Fixed in https://github.com/markusfisch/BinaryEye/commit/39f95a1c04ec535fbb1ddf87738f2e73fa952940
