### ISSUE TITLE
CODE 128 Broken in latest F-Droid update

### ISSUE THREAD

**Issue by qcasey** [markusfisch/BinaryEye#306]
Hello, thanks for the great app! F-Droid updated from 1.52.0 to 1.54.0 recently and now scanning USPS barcodes (CODE 128) are read as binary data, and any HTTP requests made subsequently fail. 

These are the same barcodes that were read properly a week ago, so the codes have not changed.

There is a suspicious space after the 8th number, the toast displays this as a left parens '(' and the More Info screen shows an ellipsis where the error is. Does this have to do with d138148cb817b3d272ca7edad8fa8c46bb38989c? 

Can anyone else confirm this is read incorrectly?

![Screen Shot 2019-02-26 at 2 24 02 PM](https://user-images.githubusercontent.com/1429672/197844735-e67bacd5-201a-4c26-8161-483ae67d63f2.png)

**Comment by markusfisch** [comment]
This is interesting! Thank you very much for reporting! 👍 

The reason for this change is that I've migrated from the original Java implementation of ZXing, the barcode reading library that powers Binary Eye, to the newer C++ fork of it. The C++ fork is much faster and, more importantly, an active project that offers new features and barcode formats (such as support for Micro QR Codes). The Java implementation is in "maintenance mode", meaning there are only bug fixes and minor enhancements.

Now, the binary data contains indeed an extra 0x1D character at position 9 - I don't know nor do I understand why that is the case yet 🤔 

But quite apart from that, it is of course wrong to treat the scan result as binary data. This contains just numbers. So I [fixed](https://github.com/markusfisch/BinaryEye/commit/105c81d4098131d436e878e9d7638cd3c5d58de5) the handling of it and know I get the HRI ([GS1 Human Readable Interpretation](https://www.gs1.org/docs/barcodes/HRI_Implementation_Guide.pdf)) formatted result: `(420)94105(92)001901755477000000000012`

There will be a new version soon!

**Comment by qcasey** [comment]
Oh wow, I did not know there was a more modern version of ZXing. That's great. Thank you for the super quick response and your help!

**Comment by qcasey** [comment]
Version 1.54.1 works perfectly. :tada:
