### ISSUE TITLE
bug Since version 1.54.0, Chinese is garbled

### ISSUE THREAD

**Issue by SunDaSora** [markusfisch/BinaryEye#309]
In previous versions of 1.52.0, it was normal to scan URLs with Chinese characters.However, after updating versions 1.54.0 and 1.54.1, scanning URLs with Chinese characters will cause the Chinese part to be garbled.The picture with the QR code is version 1.54.1, and the picture without the QR code is version 1.52.0. You can see that one is normal, while the Chinese part is garbled.
![Screenshot_20221030-094415_Binary Eye](https://user-images.githubusercontent.com/49709661/198858973-9ec523f4-0dad-49fa-a0a8-87798294c700.png)
![Screenshot_20221030-094437_Binary Eye](https://user-images.githubusercontent.com/49709661/198858982-ce3f719e-b8ab-4eb8-9ecf-b7468ec61829.png)

**Comment by markusfisch** [comment]
Sorry for this bug 🙈  And thanks for filing an issue 👍 This is wrong, of course.

May I ask for the original QR Code to debug this?

**Comment by markusfisch** [comment]
Nevermind, I found the problem 😉 Fixed in Version 1.55.0 which should become available soon.

**Comment by SunDaSora** [comment]
Yes, here it is.
![qr_code_https](https://user-images.githubusercontent.com/49709661/198885705-5e687cb5-625a-4e07-a1ff-1eca4dc4b32a.png)

**Comment by SunDaSora** [comment]
This is not a real URL, it's just an example.

**Comment by markusfisch** [comment]
Thank you!

I just verified that Version 1.55.0 indeed does fix the bug on this QR Code 😄
