### ISSUE TITLE
Chinese content is missing, and the generated QR code is incomplete.

### ISSUE THREAD

**Issue by SunDaSora** [markusfisch/BinaryEye#310]
Version 55 can scan Chinese QR, but the content will be lost when it is generated.
The white phone uses version 55, and the black phone uses version 52.
Original Chinese text content:
想去315投诉一波，真的很讨厌，我记得之前微软就有一次这样然后被罚的
![qr_code___315](https://user-images.githubusercontent.com/49709661/199645230-400b2ff3-e5ff-4e16-bedf-ba07dfc5bdbf.png)
![IMG_20221103_115700](https://user-images.githubusercontent.com/49709661/199645231-e1e0ada8-cc8d-45a8-9c9f-b623a537e2a5.jpg)

**Comment by SunDaSora** [comment]
Japanese also has the problem of lost content of generated QR code.

**Comment by markusfisch** [comment]
Thanks for filing an issue! 👍 This is a bug, of course. Sorry for the inconvenience.

Fixed in https://github.com/markusfisch/BinaryEye/commit/ba24287f04697703b245e34dec6f9a0f719cc360

A new version will be available soon! Thanks again for catching this!
