### ISSUE TITLE
QRCodes containing tabs are treated as binary data

### ISSUE THREAD

**Issue by GHolk** [markusfisch/BinaryEye#311]
When the qrcode contains tab characters, the scaning result UI does not allow user to copy as text or share as text.

example QRCode:

![example qrcode](https://user-images.githubusercontent.com/13307281/199916394-8f87f013-0977-48a0-876f-f2b11cd316ee.png)

(generated with https://www.nayuki.io/page/qr-code-generator-library)

**Comment by markusfisch** [comment]
Ah, yes, this is a bug in the barcode library 😬 Thanks for filing an issue! 👍 

Will be fixed soon.

**Comment by markusfisch** [comment]
Fixed in Version 1.56.1 which should become available within the next few hours on Google Play.

If you don't want to wait, you can get it directly from GitHub:
https://github.com/markusfisch/BinaryEye/releases
