### ISSUE TITLE
how to filter barcode at multi barcode screen

### ISSUE THREAD

**Issue by ggininder5566** [markusfisch/BinaryEye#312]
Hello, guys

In my use case, i want to filter a 1D barcode at multi barcode screen

But in BinaryEye ,it seems to detect barcode randomly .

Is there any way I can get the result of all barcodes on the screen and filter it?

Tanks all

**Comment by markusfisch** [comment]
Hi, yes, there are two options: either use the cropping window (and bring it in a shape that matches your barcode of interest) or restrict the recognized formats (temporarily) to the 1D format of the barcode you want to scan.

You can easily do this with the overflow menu (the three dots in the upper right corner).

**Comment by ggininder5566** [comment]
> Hi, yes, there are two options: either use the cropping window (and bring it in a shape that matches your barcode of interest) or restrict the recognized formats (temporarily) to the 1D format of the barcode you want to scan.
> 
> You can easily do this with the overflow menu (the three dots in the upper right corner).

ok, I got it.
Thank your reply
