### ISSUE TITLE
Feature request: audible feedback on code recognition

### ISSUE THREAD

**Issue by kk-konrad** [markusfisch/BinaryEye#318]
either beep with configurable frequency/duration or selection of a custom sound file in order to being able to distinguish the sounds of a small number of devices.

This feature would be much appreciated. It would improve our experience in certain settings, e.g.
a small group  of  people scanning all books for inventory in our public library. While pulling books off the shelves one by one and scanning the vibration feedback can easily be missed.

Thanks very much for providing  this app!

**Comment by markusfisch** [comment]
Ah, yes, this was requested before, and there will be an option to enable audible feedback soon.

**Comment by kk-konrad** [comment]
Nice, thanks very much!

**Comment by markusfisch** [comment]
Version 1.57.0 finally adds audio feedback.

The update should become available within the next few hours on Google Play.

Alternatively, it is already available directly from GitHub:
https://github.com/markusfisch/BinaryEye/releases/tag/1.57.0
