### ISSUE TITLE
'Copy to clipboard' and 'Share as TXT' produced unacceptable results

### ISSUE THREAD

**Issue by meiMingle** [markusfisch/BinaryEye#322]
The following code may need to be optimized because it produces results like this

> █████████████████████████████
█████████████████████████████
████ ▄▄▄▄▄ █▀█ █ █ ▄▄▄▄▄ ████
████ █ █ █▄█▄▄▀█ █ █ ████
████ █▄▄▄█ █ ▄▄█ █▄▄▄█ ████
████▄▄▄▄▄▄▄█ █▄█▄█▄▄▄▄▄▄▄████
████ ▄▀▄██▄▄▀█▄ ▄▀▄▄▄█ ▀████
████ ▄▀▀█▄ ▀█▄▄▀ ▄█▀█▀ ████
███████▄▄▄▄█▀▄ ▄█▀ ██▀▀█▄████
████ ▄▄▄▄▄ █▄█▀▄▄█ ▀██ ▀████
████ █ █ █▀ ▄█▄ ▀▄▄ ▄▀████
████ █▄▄▄█ █▀█▀ ▀▄▄▀█▀ ▀ ████
████▄▄▄▄▄▄▄█▄█▄██▄█▄███▄█████
█████████████████████████████
█████████████████████████████

https://github.com/markusfisch/zxing-cpp/blob/416ffd8fe7473d2620a20ec2a75f5aab901ead7c/wrappers/aar/zxingcpp/src/main/java/de/markusfisch/android/zxingcpp/ZxingCpp.kt#L288

**Comment by markusfisch** [comment]
Well, this is intentional 😉 

See, the text representation looks distorted because of the variable width font.

With a monospace font, it looks like this:

```
█████████████████████████████
█████████████████████████████
████ ▄▄▄▄▄ █▀█ █ █ ▄▄▄▄▄ ████
████ █   █ █▄█▄▄▀█ █   █ ████
████ █▄▄▄█ █   ▄▄█ █▄▄▄█ ████
████▄▄▄▄▄▄▄█ █▄█▄█▄▄▄▄▄▄▄████
████▄ █ █▀▄ ▀▀▄ ▄▀▄ ▄█▄ █████
████   ▄▀█▄█▄█ ▄▀▀    ▄▀ ████
████▄██▄██▄▄ █ ▄█   ▀█▄█▄████
████ ▄▄▄▄▄ █▄ ▀▄▄█ ▀▄▄█ ▀████
████ █   █ █▀ ▄█▄  ▀█ ▄▄▀████
████ █▄▄▄█ █▀▄█ ▀▄▄▄▄ █▀ ████
████▄▄▄▄▄▄▄█▄████▄█▄▄██▄█████
█████████████████████████████
█████████████████████████████
```

**Comment by markusfisch** [comment]
Hm, that's interesting 🤔 Unfortunately, I cannot reproduce this 😬 When I share or copy the text representation into an E-Mail (in my case the GMail app for example), the message still contains all spaces when I receive it. Same when sharing or pasting into the Slack app.

May I ask what Android version you are running?

**Comment by meiMingle** [comment]
> May I ask what Android version you are running?

Android 11

**Comment by meiMingle** [comment]
Is there any other information needed to move this issue forward?

**Comment by markusfisch** [comment]
Well, anything that would help me reproduce this issue would be good 😬 I've tested it Android 11 and it works for me there, so this can't be the problem.

Do you have any special clipboard apps installed that might mess with what's on the clipboard?

Do you have access to another device and can you reproduce the issue there?

**Comment by meiMingle** [comment]
> Do you have any special clipboard apps installed that might mess with what's on the clipboard?

Perhaps you're right. But it's a bit hard for me to find it, because I'm not even an Android beginner, and I have too many frameworks/plugins/apps installed on my phone, such as magisk, LSPosed, ADM, Via, ProxyDroid..... .. This weekend, I will try my best to learn the real machine debugging of Android, and try to find the problem.

**Comment by meiMingle** [comment]
> Do you have access to another device and can you reproduce the issue there?

I reproduced this problem on another Android9 device, the following are the details of the two android devices in my hands.

| Device Name    | Model   | Android version | OS           |
| -------------- | ------- | --------------- | ------------ |
| Realme GT Neo2 | RMX3370 | 11              | realmeUI 2.0 |
| Realme Q       | RMX1971 | 9               | ColorOS 6.0  |

**Comment by meiMingle** [comment]
Oh, it was a misunderstanding, now I see that the problem is not with BinaryEye, the problem is with the tool I use to share text from mobile to PC device.

**Comment by markusfisch** [comment]
No problem, happy you found it 👍
