### ISSUE TITLE
sharing to Binary Eye from browser does not generate barcode

### ISSUE THREAD

**Issue by travisfw** [markusfisch/BinaryEye#328]
I opened a url in the browser from an email, and wanted to open that url on another tablet, so I shared the url, selected Binary Eye from the list, and Binary Eye compose activity opened, but with no data. I retried a few times, and eventually junt copied the url and pasted it into the text area at the bottom of the compose activity.

To Do: Either disable Binary Eye as a way to share, or make sharing via intent to Binary Eye actually compose a QR code.

**Comment by markusfisch** [comment]
This is a bug 🙈 The shared text should appear in the Compose screen.

Thanks for reporting!

**Comment by markusfisch** [comment]
Fixed in https://github.com/markusfisch/BinaryEye/commit/7a327ab7c44192d47dc4885826f5109f13acc7cc

A new version will be available soon!
