### ISSUE TITLE
Unicode text in qr-code support

### ISSUE THREAD

**Issue by password123123123** [markusfisch/BinaryEye#34]
Trying to scan qr generated from cyrilic letters and got "binary data" instead.

**Comment by markusfisch** [comment]
Hm, that's quite interesting and definitely a bug - thanks a lot for reporting!

I guess it must have something to do with the UTF-8 encoding but I don't quite understand what's going wrong. The app classifies data as binary if there are bytes between 0x00 and 0x08 and/or between 0x0e (14) and 0x1f (31). UTF-8 code points start at 0xc0 (192).

Do you see bytes between 0x00 - 0x08 and/or 0x0e - 0x1f in the hex dump when you're scanning the QR code?

**Comment by password123123123** [comment]
Sorry, i think its a bug in firefox qr generator plugin, i used. I try another scanner from fdroid with same result.

31 трав. 2019, 14:00 з notifications@github.com:
