### ISSUE TITLE
{META} is not populated

### ISSUE THREAD

**Issue by george-hopkins** [markusfisch/BinaryEye#346]
Since the migration to ZXing-C++ the URL parameter `{META}` is not populated anymore. I don't need it personally though. I'm happy to send a PR if you'd like me to remove it from the documentation.

**Comment by markusfisch** [comment]
Ah, thanks! 👍  Totally forgot to remove it 🙈 

Fixed in https://github.com/markusfisch/BinaryEye/commit/6dff9992d8edd8016991393fee960f879b155d30
