### ISSUE TITLE
Binary Eye (version 1.8.1) says "No application can open that"

### ISSUE THREAD

**Issue by chrisbarth01** [markusfisch/BinaryEye#35]
#### Expected behavior 
I expected the app to perform a search about the product using the details gotten from the barcode. 

---

#### Actual behavior 
After the barcode is scanned, I clicked on the 'open URL' button and the app says "No application can open that" whereas I have a lot of applications which can open the link.

---

#### How to reproduce 
- Download, install and launch the latest version of the app
- Grant the required permission and scan a barcode 
- Click on the 'open URL' icon at the top right corner of the screen (the middle icon) 
- Observe the bug.

---

Device: Gionee f100s 
Android version: v6.0
App version: v1.8.1

---

#### Recording of the bug
![20190614_114113](https://user-images.githubusercontent.com/49325171/59509495-12f25780-8ea9-11e9-8c49-5bd4938028fa.gif)

**Comment by molikuner** [comment]
Hey, thanks for the suggestion. There is already a problem with that. At least I would put it in the same category. (#18) Don't hesitate to comment there and explain in more detail how the search should be done.

Google search or equivalent service? There are any special databases that contain information about products? Although I can't name them explicitly, I know they exist.

What kind of search should be performed?

**Comment by chrisbarth01** [comment]
If it's a link, the link should be searched for, and if it's numbers, the numbers should be searched for...... Take a look at what happened when I searched Google for that number scanned by the app.

**Comment by chrisbarth01** [comment]
If it's a link, the link should be searched for, and if it's numbers, the numbers should be searched for...... Take a look at what happened when I searched Google for that number scanned by the app. 
![20190614-160806](https://user-images.githubusercontent.com/49325171/59519073-f95c0a80-8ebe-11e9-8ca5-eff3da874623.png)

**Comment by chrisbarth01** [comment]
That's the product I was actually holding 🤷‍♂....

**Comment by markusfisch** [comment]
Fixed in https://github.com/markusfisch/BinaryEye/commit/78bb03fabfb3d7dcff9bfbd8c56fcc4fc3b58a9d

Now, instead of showing a boring error message, the app tries Google with contents that cannot be resolved.
