### ISSUE TITLE
Do not auto-close without camera access

### ISSUE THREAD

**Issue by NePoCz** [markusfisch/BinaryEye#351]
Currently, the app will close when camera access is denied. But it should work perfectly fine for scanning images from gallery even without camera access & you can still generate codes. Why auto-close it, when other functions cas still be used? I understand this is a not a common use case, but not impossible either

**Comment by markusfisch** [comment]
Yes, that's right!

I will change this with the next version.

**Comment by markusfisch** [comment]
Fixed in https://github.com/markusfisch/BinaryEye/commit/7dfd7a130320115c291fc1f34dfc137fb74876b7

**Comment by NePoCz** [comment]
Great, thanks for the fast fix and awesome app. A small question comment though - I didnt see any changes to the toast message as part of the commit. It currently says "This app does not make any sense without camera access. Good bye." which naturally wouldnt make sense any more.

**Comment by markusfisch** [comment]
You're right! 👍 Removed this message in https://github.com/markusfisch/BinaryEye/commit/a489f3aa22af5163e9ecd0ad60164ccb10eefb56
