### ISSUE TITLE
Missing release 1.58.2

### ISSUE THREAD

**Issue by Sertonix** [markusfisch/BinaryEye#354]
In the f-droid store the last version of binary eye is 1.58.2 .
But last release on this repo shows 1.58.0 .
Could the lates release be added?

**Comment by markusfisch** [comment]
Ah, yes, I just forgot to add the latest release on GitHub 🙈

It's now available:
https://github.com/markusfisch/BinaryEye/releases/tag/1.58.2
 
Thanks for pointing this out 👍
