### ISSUE TITLE
Incorrect error correction level used when generating QR codes

### ISSUE THREAD

**Issue by mantas-p** [markusfisch/BinaryEye#357]
When QR is generated using L, M or Q EC setting, resulting code has L EC level, with H EC setting code comes out as M.
This happen both when generating codes manually, and when code is displayed after scanning. EC level is correctly recognized for scanned code, only regenerated image is incorrect.

**Comment by markusfisch** [comment]
This is a bug 🙈 Thanks for reporting 👍 

Fixed in https://github.com/markusfisch/BinaryEye/commit/24766f55d4e3cd07e835986b87a53a762b0c8834

A new version will become available soon.

**Comment by mantas-p** [comment]
Thanks for update. Code generated manually is now correct, but one shown after scanning still uses different EC level than what was scanned.

**Comment by markusfisch** [comment]
You're right! I was thinking about that when I was fixing it but forget this part somehow 🙈 Thanks for reminding me! 👍 

Fixed in https://github.com/markusfisch/BinaryEye/commit/b4d66e28e272ed1f6a6c0a6355a26b624dd37ed4
