### ISSUE TITLE
Idea: Add Spotify Codes

### ISSUE THREAD

**Issue by Dtrieb** [markusfisch/BinaryEye#368]
What do you think about the idea to add Spotify Codes?

https://www.spotifycodes.com/index.html

**Comment by markusfisch** [comment]
Hm, I just see "Not Found" when I visit this URL 🤔 

What are Spotify Codes?

**Comment by Dtrieb** [comment]
> Hm, I just see "Not Found" when I visit this URL 🤔

Damn you have to remove the index.html
https://www.spotifycodes.com

> What are Spotify Codes?

Codes from Spotify to open songs, playlists, etc.
See the website.

**Comment by markusfisch** [comment]
Ah, thanks for the clarification! 👍  Didn't know this.

Unfortunately this looks like proprietary bar code format. I didn't find a technical specification or description, and while it's probably possible to reverse engineer how it works, the question is why bother? 😉 What could it be good for to read this bar code? 🤔

**Comment by spacesynth** [comment]
I am not saying we need this, or don't need this. I just found the format interesting and searched if someone reversed it:  
https://github.com/ozgecinko/SpotifyCodeGenerator  

Medium post explaining the barcode format, archived for convenience:  
https://archive.ph/RvC72

**Comment by markusfisch** [comment]
Thanks for the links! Really interesting! 🤔 

However, this is probably more for [ZXingCpp](https://github.com/zxing-cpp/zxing-cpp), the barcode library this app is using 😉

@axxel would you be interested in this?

**Comment by axxel** [comment]
Thanks for pinging me. Before I saw the link list, I was hunting for some information myself and also ended up at
 * https://boonepeter.github.io/posts/2020-11-10-spotify-codes/ and
 * https://boonepeter.github.io/posts/spotify-codes-part-2/

But understanding that even if you ended up detecting and decoding the barcode, you'd still only get the "meadia reference" number which you can only translate into a spotify URI with an active account and an online lookup in their database. So decoding this in zxing-cpp does not sound very useful at all to me. Bottom line: I'll not invest any time in this. ;)
