### ISSUE TITLE
Datamatrix bytes not decoded correctly in the range from 0x80 to 0xFF

### ISSUE THREAD

**Issue by wiktorpp** [markusfisch/BinaryEye#380]
I noticed that the app doesn't correctly decode datamatrix codes with bytes in the range from 0x80 to 0xFF. I tested with the version of the app from [here](https://github.com/markusfisch/BinaryEye/releases/tag/1.60.3) and [pylibdmtx](https://github.com/NaturalHistoryMuseum/pylibdmtx)

Examples:
80 -> C2 80
81 -> C2 81
A0 -> C2 A0
E0 -> C3 A0
F0 -> C3 B0
FF -> C3 BF

It's possible that it's an issue with pylibdmtx, but I've tested with another [code sccanner](https://qrcode-decoder.com/), and it looks to me like it's giving me the expected output

**Comment by markusfisch** [comment]
Hm, is it possible to share the DataMatrix code in question? 

Unfortunately, I cannot reproduce this.

**Comment by wiktorpp** [comment]
> Hm, is it possible to share the DataMatrix code in question?
> 
> Unfortunately, I cannot reproduce this.

00 00 -> ![0000](https://github.com/markusfisch/BinaryEye/assets/56189344/c28fcff4-71a9-4039-83a2-ad403772096c) -> 00 00
00 FF -> ![00FF](https://github.com/markusfisch/BinaryEye/assets/56189344/190ebcb5-deed-4197-8c9c-2672c1c9a893) -> 00 FF
FF FF -> ![FFFF](https://github.com/markusfisch/BinaryEye/assets/56189344/687b88a9-6844-4422-8926-1026679134a2) -> C3 BF C3 BF
80 80 -> ![8080](https://github.com/markusfisch/BinaryEye/assets/56189344/4088b5d0-178c-4acf-aaf7-160eb239f44f) -> C2 80 C2 80
