### ISSUE TITLE
'Forward scans' enabled by default?

### ISSUE THREAD

**Issue by drws** [markusfisch/BinaryEye#382]
The option _Forward scans_ is enabled by default. Even though it probably does nothing without the URL, it's still needlessly suspicious.

**Comment by markusfisch** [comment]
Sorry for the late answer 🙈 From version 1.63.0 on Forwad scans is disabled by default (see https://github.com/markusfisch/BinaryEye/commit/21c29ca373815015a3043fedaac1931fc6c4633a).

The reason it was enabled by default was that this setting came after giving an URL to send to, and I didn't want to annoy existing users using this feature already by disabling the forwarding with an update. But this was some time ago, and I guess the setting exists now where ever it was used.
