### ISSUE TITLE
Cropping limiter is too small

### ISSUE THREAD

**Issue by elesto** [markusfisch/BinaryEye#385]
![Screenshot_20230811-075156](https://github.com/markusfisch/BinaryEye/assets/24771215/84c7907c-a72c-4456-b176-2e0f36870848)
It is not possible to scan codes using the default crop setting. Please change it to a square.
Phone: Xperia 5 ii

**Comment by elesto** [comment]
Seems to be fixed now but im unsure if this issue is the reason

**Comment by markusfisch** [comment]
Hi, and sorry for not answering sooner 😬 I somehow missed this one 🙈 

Please enable "Show cropping limiter" in the settings, and you will have a handle in the lower right corner of the cropping window that allows you to change its size. You can also drag the handle to the center of the screen to simply use the whole screen and not have a cropping window.
