### ISSUE TITLE
Request to add a field with advanced options for generating barcodes.

### ISSUE THREAD

**Issue by DienoX** [markusfisch/BinaryEye#387]
Hi,
Is it possible to add a text field in which advanced options for barcode generation would be entered?
The parameters are available on the website of the library used by binaryeye.

I need this option to add margins to barcodes and to create more advanced codes.

**Comment by markusfisch** [comment]
Hi, yes, this would be possible, but a text field would probably be too opaque. A user would have to know what to enter, and the app would have to parse the text.

So I think it would be better to use dedicated controls for each property. There aren't that many options after all.

I will try to add this as soon as I find the time.

**Comment by DienoX** [comment]
Thank you very much for that

**Comment by markusfisch** [comment]
Implemented in https://github.com/markusfisch/BinaryEye/commit/a4b639edfe3fb36ecffb956afb6912a76dcd5e2f

Will be in the next release 😄

**Comment by DienoX** [comment]
Thank you very much.
Are you going to add Wear OS support? The application closes when entering history. I'm very sorry for the other thread.
