### ISSUE TITLE
Wrong decoding with complex datamatrix code

### ISSUE THREAD

**Issue by eule68** [markusfisch/BinaryEye#391]
I encountered a wrong decoding with a complex datamatrix code. The code has 96 bytes but was decoded with 97 bytes. One byte were decoded wrong compared to 2 reference scanners. I used Scanbot and a commercial machine vision toolbox (Matrox MIL) as reference with identical readings.

As you can see from the attached files BE decodes the 6th character with C3 followed by a 96 what originally was a D6.

Sample code attached.
![code1](https://github.com/markusfisch/BinaryEye/assets/66522030/1596e89a-d32c-444d-888a-0299017a3005)
![Binary Eye](https://github.com/markusfisch/BinaryEye/assets/66522030/37830bab-5b6d-4cc4-ad71-97015d590f91)
![Scanbot SDK Barcode Scanning](https://github.com/markusfisch/BinaryEye/assets/66522030/b06361a5-fe4a-4802-8d97-ecdaf343b82e)
[Binary Eye.txt](https://github.com/markusfisch/BinaryEye/files/12505728/Binary.Eye.txt)
[Scanbot.txt](https://github.com/markusfisch/BinaryEye/files/12505729/Scanbot.txt)

**Comment by markusfisch** [comment]
Hm, that looks like a UTF-8 issue 🤔 Thanks for filing an issue! 👍 And sorry for the late reply.

Will investigate…

**Comment by markusfisch** [comment]
Fixed in https://github.com/markusfisch/BinaryEye/commit/a098fcb48cb77d2b227875de17e7cfa39a4d744d

There will be a new version soon.
