### ISSUE TITLE
Can i use this plugin in my ionic cordova project 

### ISSUE THREAD

**Issue by Cap-7** [markusfisch/BinaryEye#395]
I need to scan a qr code which should return a hexadecimal value, rather than actual string.  Is it possible to achieve it using this plugin in ionic?

**Comment by markusfisch** [comment]
Well, this is a native Android app, not a plugin. I don't know anything about ionic, sorry.

But there is https://github.com/markusfisch/BarcodeScannerView which is an Android library that can be used in Android apps. Maybe there is a way to use this from ionic?
