### ISSUE TITLE
v1.61.0 Fails to access camera, LineageOS 20, Android 13 Fxtec Pro1-x

### ISSUE THREAD

**Issue by Mhowser** [markusfisch/BinaryEye#403]
Device: Fxtec Pro1-x 8gb variant, model QX1050

Operating system: LineageOS version 20-20231030-NIGHTLY-pro1x, no GAPPS or MicroG, Rooted with Magisk.

Crash logs: 
 - logcat [binary-eye-02-11_22-03-51.log](https://github.com/markusfisch/BinaryEye/files/13257665/binary-eye-02-11_22-03-51.log)
- [crash.log](https://github.com/markusfisch/BinaryEye/files/13257668/crash.log)
- [device.txt](https://github.com/markusfisch/BinaryEye/files/13257669/device.txt)
- [dump.log](https://github.com/markusfisch/BinaryEye/files/13257670/dump.log)
![Screenshot_20231104-134118_Binary Eye](https://github.com/markusfisch/BinaryEye/assets/24195572/5323e414-d744-4aaa-a119-5eab42266584)

**Comment by Mhowser** [comment]
I just did some testing and found out that the selfie camera works and can scan codes 
![Screenshot_20231106-163242_Binary Eye](https://github.com/markusfisch/BinaryEye/assets/24195572/533cf521-56f2-4eb2-a259-9e62c28f6b69)
Very odd, I didnt change any system configurations.

**Comment by Mhowser** [comment]
here is another log while using the front camera sensor [recorded.log](https://github.com/markusfisch/BinaryEye/files/13274183/recorded.log)

**Comment by Mhowser** [comment]
Everything works great now that I updated LineageOS to `20-20231113-NIGHTLY-pro1x`

**Comment by markusfisch** [comment]
Ah! Great! And thanks for letting me know what resolved the problem 👍
