### ISSUE TITLE
What does 'Barcode formats' setting do?

### ISSUE THREAD

**Issue by elvekdarzhinov** [markusfisch/BinaryEye#404]
Can't find any difference in behavior

**Comment by markusfisch** [comment]
What do you mean? "Restrict format" from the overflow menu (the three dots in the upper right)?

**Comment by elvekdarzhinov** [comment]
No, I'm talking about this option:
![screenshot](https://github.com/markusfisch/BinaryEye/assets/90803167/5167acdf-7cb9-4d0f-88f4-e2f301f1cded)

**Comment by markusfisch** [comment]
Ah! This is supposed to permanently restrict scanning to the enabled formats - which does not work in the current version as I just noticed 😳🙈 

Thank you for pointing this out to me! 👍  Will be fixed with the next version.

**Comment by markusfisch** [comment]
Fixed in https://github.com/markusfisch/BinaryEye/commit/35b110a472532de85209bb250122b22dcf80f2c7

**Comment by elvekdarzhinov** [comment]
🔵🦔⚡
