### ISSUE TITLE
Could not send email

### ISSUE THREAD

**Issue by biopsin** [markusfisch/BinaryEye#409]
Hi,
thank you for a sweet little code scanner. 
Unfortunately I'm not able to send the email when scanning a QR CODE formated below and selecting the email icon upon detection.

(Example used from [Superuser](https://superuser.com/questions/249945/how-do-you-create-a-qr-codes-that-creates-an-email-that-includes-pre-drafted-inf))

The syntax is
```
MATMSG:TO:john@example.com;
SUB:Some subject text here;
BODY:Some body text here;;
```

I have to specify that Im using Lineageos-18.1   BinaryEye-1.61.1   Fairemail-1.2075  but I have deactivated the default mail client, and 
I suspect this is the main issue, what do you think?

**Comment by markusfisch** [comment]
Hello and thanks for filing an issue about that! 👍 

Is there an error message when you tap on the mail button?

The mail button is simply creating a [ACTION_SENDTO](https://developer.android.com/reference/android/content/Intent#ACTION_SENDTO) intent, which should [open the default mail client](https://developer.android.com/reference/android/content/Intent#Email).

So yes, if you haven't set anything as your default mail client, this may be the reason 😬

**Comment by biopsin** [comment]
Thank you for the reply;
> Is there an error message when you tap on the mail button?
only `Could not send email`
I'll be doing a update this weekend and I'll test reinstalling the lineage email client and see what happens, may be I only need to set a default selecting Fairemail first time and then uninstall it again..

**Comment by markusfisch** [comment]
Well, Binary Eye is using the [default way](https://developer.android.com/reference/android/content/Intent#Email) of how apps can send mails.

So there's not much Binary Eye could do, apart from letting you configure, in the app, what Intent to fire when you want to send a mail. Of course, it would be highly unusual to have something like this in an app. After all, that is why there are things like default apps.

Do you have any other app where sharing into you mail app works?

**Comment by biopsin** [comment]
Ok, for some reason it just started working, I think its the way I create the mail QR code and linebreak it.
Im closing it as local user error.
Have a nice day.

**Comment by markusfisch** [comment]
Thanks for the info! I'm glad it's working now! 😄
