### ISSUE TITLE
[bug] Zoom set on startup

### ISSUE THREAD

**Issue by tippfehlr** [markusfisch/BinaryEye#412]
Since some update (can't name a date sadly) BinaryEye starts with a bit over 50% zoom.

Everything after that works fine

**Comment by markusfisch** [comment]
Thanks for filing an issue about this 👍 

Strange thing 🤔  Even when you drag the zoom slider to a lower zoom level (or did you mean the lowest possible is 50%?), leave the app and come back to it?

**Comment by tippfehlr** [comment]
Thanks for the quick response too! Are there logs somewhere that I could share?

**Comment by tippfehlr** [comment]
I do not know if there was an update, but the issue has been resolved magically and the zoom now starts at 0%.

**Comment by markusfisch** [comment]
Hm, very strange 🤔  Yes, there was an update, but I didn't change anything in that department.
