### ISSUE TITLE
Feature request: Adding note before saving to history

### ISSUE THREAD

**Issue by tiborepcek** [markusfisch/BinaryEye#419]
Hi and thank you for this super useful app. I especially love forwarding.

Could you please add a feature which allows me to add a note for every scanned barcode, so I can see in history what barcode represents what product? I know you can name the saved item in history, but I would really appreciate it if this could be done before saving to history.

Also, the note (or the name) should be added to the history export file, if possible.

**Comment by tiborepcek** [comment]
Hi @markusfisch and many thanks for adding label in decoding screen in version 1.63.0, I really appreciate it!

If you also could add the label to the history export file (Share as file), that would be great.

**Comment by markusfisch** [comment]
Oh, of course, I just forgot to add it there too 🙈 Thank you for pointing this out to me! 👍 

And sorry for not responding to this issue earlier.

It's now in [1.63.1](https://github.com/markusfisch/BinaryEye/releases/tag/1.63.1), which should become available in Google Play within the next few hours or so.

**Comment by tiborepcek** [comment]
No worries at all. Updated from Github and it works like a charm. 👍
