### ISSUE TITLE
Idea: Display custom text from webhook during continuous scan

### ISSUE THREAD

**Issue by anthonyryan1** [markusfisch/BinaryEye#429]
Right now when scanning serials, each serial is shown in a toast at the bottom of the screen.

An idea I think could have some utility would be to allow the webhook to provide custom text to show in that toast.

Examples include
- "Warranty: Valid" or "Warranty: Expired" when scanning serials
- "17 / 20" when inventory scanning a large number of de-duplicated barcodes for inventory tracking

Would this sort of functionality be welcome in BinaryEye?

**Comment by markusfisch** [comment]
It should already work that way! 😉

If the response from the server has a body, the first 240 bytes of it are shown in the toast.
