### ISSUE TITLE
[Feature Request] Add History/Verlauf in this Menü 

### ISSUE THREAD

**Issue by Dtrieb** [markusfisch/BinaryEye#442]
Could you please add Verlauf/History in this Menü?

![Screenshot_20240325-124849](https://github.com/markusfisch/BinaryEye/assets/3650284/230fd200-22fe-4a60-a046-befa59e86f94)

**Comment by markusfisch** [comment]
Sure! Implemented in https://github.com/markusfisch/BinaryEye/commit/48ed5f1a2c8b8108b9034e29db169f3ebc28ad6e

Will be in the next update!
