### ISSUE TITLE
[Enhancement request] FrameQR

### ISSUE THREAD

**Issue by Yenya** [markusfisch/BinaryEye#444]
Hello,

apparently there is a special standard for QR codes with logos or other non-QR things embedded in the middle, as opposed to standard practice of just overlapping the logo over the QR code and letting the error correction handle the damage. It is called FrameQR, and it would be nice if BinaryEye can read it:

https://www.denso-wave.com/en/system/qr/product/frame.html

I am not sure whether there is a free specification of FrameQR.

Thanks in advance for considering this!

-Yenya

**Comment by markusfisch** [comment]
Hi Yenya, thanks for the input!

This would be a request for [ZXingCpp](https://github.com/zxing-cpp/zxing-cpp), the barcode scanning library this app is using.

By the way, you most probably know this already, you can already overwrite a significant portion of any ordinary QR Code (with a logo) when using a high error correction level. Of course, not quite the same as a FrameQR, but maybe also an option.
