### ISSUE TITLE
Codabar scans omit start/stop codes

### ISSUE THREAD

**Issue by QJKX** [markusfisch/BinaryEye#445]
Codabar codes can start/stop with ABCD. Keeping this information is essential for cloning the barcode (eg a library card). Without it the generated barcode won't necessarily scan in it's original context.

https://github.com/zxing/zxing/issues/109#issuecomment-828417585
>If the code starts and stops with the same character it is complete.
>If it stops with a different character, there is a continuation code to scan.
The data should be concatenated.

https://github.com/zxing/zxing/issues/179#issuecomment-47840840

>You can specify the hint DecodeHintType.RETURN_CODABAR_START_END to have them returned as part of the content.

**Comment by markusfisch** [comment]
Thanks for filing an issue about that! 👍 

I just [enabled](https://github.com/markusfisch/BinaryEye/commit/24c7ad0ba47b08eaa665246feada89e1b9070935) returning the start/stop codes so this will be in the next update.
