### ISSUE TITLE
[Feature request] Display hash at the bottom of the results

### ISSUE THREAD

**Issue by spacesynth** [markusfisch/BinaryEye#452]
I’m grateful for Binary Eye’s ability to simultaneously display hex values and text. I frequently scan large 2D codes, such as my train ticket, to determine if I need to replace it with a newer version in my Android wallet.

Since the mask patterns are not always the same in the ticket, a comparison by eye is unreliable.

These data fields aren’t human-readable either, but a hash beneath the results (like the popular SHA256) would make it easier to identify changes when comparing two large 2D barcodes. While this may be a niche use case, it’s a practical solution for comparing non-human readable data.

**Comment by spacesynth** [comment]
This is great and I love you want to add it! Any checksum is good, but be prepared that people will judge us if we opt for md5 or sha1 since they are considered unsafe (only when used in actual cryptography) but people will disregard that other use cases are  legitimate.

else a pseudocode example for ```sha256_with_newline = sha256[0:15]+"\n"+sha256[16:31]``` to wrap it?

I don't know what other people will use it for, but I see how the people obsessed with their cryptocurrencies might print out codes for a paper wallet, or a more legit use: You backup your ssh_priv.key and you sha256 sum the data on your machine and sha256 sum the data from the QR.

Sound useful for anyone in that case? If I can convince you to use an ugly 32 byte char split in 16+16 byte over a newline, maybe people will not hate me for saying: "Yeah, md5 would be fine to, but..."

No matter how you decide one hash might be enough, many thanks! I don't want to start the feature creep. Else a dropdown menu in options to select one would be okay. But I really would feel guilty to make you go out of your way and implement more than one feature for a request by a stranger.

**Comment by markusfisch** [comment]
I finally decided to add a setting to choose the hashing algorithm.

There's a new version [1.63.8](https://github.com/markusfisch/BinaryEye/releases/tag/1.63.8) which should become available on Google Play soon!

**Comment by spacesynth** [comment]
Thank you! Also writing to suggest something:
Among artists I've supported Ko-Fi is pretty popular. They are exactly like buymeacoffee, but they still offer PayPal.
Sender and receiver name are safeguarded from each other, there are no fees.

So I would donate if you would off more flexible services than buymeacoffee and less volatile ones like bitcoin.
Unless you don't have a PayPal Ko-Fi does everything better than the current methods.

https://ko-fi.com/
This is not an ad, just a suggestion for hidden free support for developers.
Cheers! Hope I can send some green for a real IRL coffee.

**Comment by markusfisch** [comment]
Thanks for the tip! I'm still trying to find my way with all these donation platforms 😉 

So I just created an account on Ko-Fi and added a button to the README 😄

**Comment by spacesynth** [comment]
![grafik](https://github.com/markusfisch/BinaryEye/assets/64961250/8816b999-1dd5-45ad-82e6-926a43d5b215)

Thanks for your trust in a new system that works better for me! Money should be yours now and glad to have a friendly dev open to feature requests. This is now backed.

**Comment by markusfisch** [comment]
Thank you very much! And thank you for using Binary Eye and for contributing this idea!
