### ISSUE TITLE
[Bug] A few selected Codes from history didn't export

### ISSUE THREAD

**Issue by Dtrieb** [markusfisch/BinaryEye#460]
If I selected a few codes on the history, click on the share button, select on of this entries

![Screenshot_20240527-123416](https://github.com/markusfisch/BinaryEye/assets/3650284/d730c134-59fa-4e7c-b519-131b52323534)

(no matter what I choose) 

I didn't get the codes in p.e. a document.

**Comment by markusfisch** [comment]
Thanks for filing an issue!

This was a bug. Fixed in https://github.com/markusfisch/BinaryEye/commit/cc2b2f076b3cbd69e4d195ca252346d7100f8c0a. A new version will come out soon!
