### ISSUE TITLE
Disable focus on tap

### ISSUE THREAD

**Issue by scoot404** [markusfisch/BinaryEye#47]
A small feature that would be useful for me. My camera's buggy due to my custom firmware, and an option to disable the focus on tap would be useful since the app crashes when I tap the screen.

**Comment by markusfisch** [comment]
Hm, that's possible, of course. Although I'd really like to know what's causing the crash 🤔 Unfortunately, I don't see any related crashes on Google Play so it's hard to tell what exactly is causing the crash.

May be it'd be better to simply add a try/catch block around the corresponding code.

**Comment by scoot404** [comment]
I can use a logcat, although I don't believe it's an issue with the app, as it happens with many other apps on my phone, not just this one.

**Comment by markusfisch** [comment]
Ah! Thanks a lot! That's just what I had in mind!

Version 1.11.1 is catching this exception now. This should fix the crash.

Version 1.11.1 will become available in the next few hours as Beta. You can opt-in for Beta here:

https://play.google.com/apps/testing/de.markusfisch.android.binaryeye

Or, if you want to try it out immediately, you may grab the APK from Releases here:

https://github.com/markusfisch/BinaryEye/releases

**Comment by scoot404** [comment]
This seems to fix the focus for me, fixing the issue. Glad I was able to inadvertently help you out. Thanks!
