### ISSUE TITLE
button change

### ISSUE THREAD

**Issue by erenonnl1** [markusfisch/BinaryEye#473]
I think it would be more useful if the create barcode button and select file from gallery buttons were switched.

**Comment by markusfisch** [comment]
Well, that depends on what you're using more often. In my case, it's clearly create barcode, but I totally understand this order is annoying to you if you're using this less often. Hm.

Maybe I add an option to change the order 🤔

**Comment by erenonnl1** [comment]
In fact, yes, you are right. people's needs can be different. as you said, if there is customization, it would be even better than most applications.
