### ISSUE TITLE
Open link in incognito mode

### ISSUE THREAD

**Issue by jech** [markusfisch/BinaryEye#475]
Hi,

When scanning a QR code containing an HTTP URL, I often want to open the link in my browser in incognito mode.  This is a little bit involved: I need to copy the link, then open the browser, then open an incognito tab, and finally paste the link.

It would be great if BinaryEye could offer the option to directly open the link in a tab in incognito mode.

**Comment by markusfisch** [comment]
Good idea! 👍 Haven't thought about this!

**Comment by markusfisch** [comment]
Turns out opening URls in inkognito mode is currently not supported on Android 😞 

Maybe it will be possible in the future.

**Comment by jech** [comment]
Thanks for investigating.
