### ISSUE TITLE
ping custom URL (or search engine) on scan

### ISSUE THREAD

**Issue by anarcat** [markusfisch/BinaryEye#48]
#37 introduced more search engines for scanned content, but it obviously doesn't cover all use cases. It would be great if we could ping arbitrary URLs with the content of the decoded bar code. my use case is to use my phone as a barcode scanner for my library collection: i could make a simple webserver that would type whatever is fed to it (with some security token or something) and use this to sort through my library.

this is a bit how [barcodetopc.com](https://barcodetopc.com/) works, except the latter made an entire other app for scanning barcode instead of reusing an existing one. it also has a custom server-side webserver that is shareware-style and has small limitations and "shareware popups".

by simply pinging a customizable URL, we could delegate this useful software to any other backend we wish...

thanks!

**Comment by markusfisch** [comment]
Yes, I see. I'm going to add the possibility to add a custom URL in the next days.
