### ISSUE TITLE
Strange permissions: Internet, Bluetooth, Location

### ISSUE THREAD

**Issue by marek22k** [markusfisch/BinaryEye#481]
Hello,

I think the app is great. However, it has a few strange features:

- It can access the internet (`android.permission.INTERNET`, `android.permission.CHANGE_WIFI_STATE`, `android.permission.ACCESS_WIFI_STATE`): Why? Why does a QR code scanner need access to the Internet?
- It can access Bluetooth (`android.permission.BLUETOOTH`, `android.permission.BLUETOOTH_ADMIN`, `android.permission.BLUETOOTH_CONNECT`): Why? Why does a QR code scanner need access to Bluetooth?
- It can access my location (`android.permission.ACCESS_FINE_LOCATION`): Why? Why does a QR code scanner need access to my location?

See also:
- https://reports.exodus-privacy.eu.org/de/reports/de.markusfisch.android.binaryeye/latest/
- https://beta.pithus.org/report/bffd965bcbbf2012942d857dc6edb9078b4f630453eba33f7d3584d8f039e28d

Maybe related: https://github.com/markusfisch/BinaryEye/issues/212

**Comment by marek22k** [comment]
Ahh, I've just discovered the “Forwarding” function in the settings. That explains it, of course. Internet for URL forwarding and Bluetooth (and therefore also location) for Bluetooth forwarding.

**Comment by markusfisch** [comment]
Yes, this app has many features 😉 

But there's a [privacy declaration](https://github.com/markusfisch/BinaryEye/blob/master/PRIVACY.md) that explains what every permission is for.
