### ISSUE TITLE
Getting a output to termux

### ISSUE THREAD

**Issue by HusniMuhammad** [markusfisch/BinaryEye#489]
How to Get the barcode/qr output directly to termux using this app intent `com.google.zxing.client.android.SCAN`

[Scheme look like this](https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intents in termux)

# Example  - `am` (actvity manger) syntax 

### 1. Setting a alarm

```
am start -a android.intent.action.SET_ALARM --ei android.intent.extra.alarm.HOUR 7 --ei android.intent.extra.alarm.MINUTES 30  --es android.intent.extra.alarm.MESSAGE "Wake up!" --ez android.intent.extra.alarm.SKIP_UI true

```

### 2. opening specific directory using file manager 

```
am start -a android.intent.action.VIEW -d "file:///storage/emulated/0/Download"
```

### 3. phone calling 
```
am start -a android.intent.action.CALL -d tel:%123456%23
```

**Comment by markusfisch** [comment]
Please have a look at the [testview/testscan](https://github.com/markusfisch/BinaryEye/blob/master/Makefile#L23) rules of the [Makefile](https://github.com/markusfisch/BinaryEye/blob/master/Makefile) 😉
