### ISSUE TITLE
"Unfortunately, Binary Eye has stopped" - all versions after Binary Eye 1.9.1

### ISSUE THREAD

**Issue by ghost** [markusfisch/BinaryEye#49]
Good day

Firstly, thank you very much for creating Binary Eye!
In my opinion Binary Eye is the best,
compared to: Barcode Scanner, SecScanQR, QR Scanner, Obsqr.

Unfortunately, in latest updates I'm encountering strange "Unfortunately, Binary Eye has stopped." error when I try to use Binary Eye for longer time.

STR:
1. Open BinaryEye
2. Play with it for few seconds
and see that it crashing with this error:
"unfortunately, Binary Eye has stopped."

Latest not affected version of BinaryEye:
1.9.1

First affected version of BinaryEye:
1.10.0

Other affected versions of BinaryEye:
1.11.0
1.11.1

Operating system:
Android 6.0.1

Compilation number:
23.5.A.1.291

Kernel version:
3.4.0-pref-gc14c2d5

Mobile phone:
Sony Xperia Z3 Compact (D5803)

Best regards

**Comment by molikuner** [comment]
Hey, could you please add a stack trace?
This would really help finding the reason for the error.
You can obtain a stack trace with you pc via `adb logcat`.

**Comment by markusfisch** [comment]
Looking into the Google Play crash logs, I think updating to the latest ZXing version may be the problem: https://github.com/markusfisch/BinaryEye/commit/b888e375567bbdd6a17f0335ee9dc93efc5adca6

I don't know why or how but I see some `NoSuchMethodError`s originating from ZXing.

Sorry for the inconvenience. I'll downgrade ZXing to 3.3.3 again and make a new release as soon as I'm home.

**Comment by Anonymous123456789012** [comment]
Awesome! Thank you very much! \o/

Seems like:

### ZXing 3.4.0
- Requires Java 8+. Note: Android apps using this version must target API 24 or higher.

Other crash reports regarding this issue:
- https://github.com/zxing/zxing/issues/1189
- https://github.com/zxing/zxing/issues/1181
- https://github.com/zxing/zxing/issues/1177
- https://github.com/zxing/zxing/issues/1170
- https://github.com/zxing/zxing/pull/1180

**Comment by markusfisch** [comment]
I've just released 1.11.2 into Beta with a ZXing downgrade to the previous version of 1.9.1. It should become available in the next few minutes or hours in the Beta channel. You may opt in here:

https://play.google.com/apps/testing/de.markusfisch.android.binaryeye

You can always go back to the production version. I usually run the app through all of Google Play's pre-launch testings to make sure everything's okay before releasing it to the public. Of course, this takes a little time. If everything works as expected, the production release should happen a couple of hours later.

If you want to try it now, you may also just simply install the APK directly from the release here:

https://github.com/markusfisch/BinaryEye/releases/tag/1.11.2

**Comment by Anonymous123456789012** [comment]
Thank you very much!
This was instant fix! \o/
I'm confirming that this issue is now fixed in Binary Eye 1.11.2.
This issue can be now closed.
