### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by Dtrieb** [markusfisch/BinaryEye#503]
https://github.com/markusfisch/BinaryEye/blob/c8c3c094db46da0da3aa20fbad23d33fd450f6e7/app/src/main/res/values-de/strings.xml#L143

Kleiner Tippfehler:  Bildschrim aufhellen -> Bildschirm aufhellen

**Comment by markusfisch** [comment]
Vielen Dank! Behoben in https://github.com/markusfisch/BinaryEye/commit/368d4dbb666f3bc5c28c647be80303f5a106016d
