### ISSUE TITLE
Unable to Compose QR code with Chinese

### ISSUE THREAD

**Issue by yzqzss** [markusfisch/BinaryEye#54]
As shown,all Chinese characters will be converted to “?”.
  
![result-2019-08-05-02-01-22](https://user-images.githubusercontent.com/30341059/62427500-728d1680-b726-11e9-81d1-ba4fbfdce258.png)
  
Although app can't compose qr code with chinese, the scan can read Chinese qr code.
  
![result-2019-08-05-02-33-01](https://user-images.githubusercontent.com/30341059/62427701-6b1b3c80-b729-11e9-8ae9-3a5ae6f235f3.png)

I only know that the QR code can supports Chinese. I don't know if other encodings have this problem.

**Comment by markusfisch** [comment]
Hopefully encoding the text as UTF-8 does fix this: https://github.com/markusfisch/BinaryEye/commit/386c7a60563dd84bd11f854dacbb13150f064da1

I've tested it with some Chinese from the internet and it _seems_ to work now. I will build a beta for you to try tomorrow.

**Comment by yzqzss** [comment]
Thanks, version 1.12.0 is ok.
