### ISSUE TITLE
Feature request: send images to BinaryEye

### ISSUE THREAD

**Issue by Iey4iej3** [markusfisch/BinaryEye#59]
I hope that BinaryEye could receive an image to read out the QR code. It is used to read a generated QR code, or an image containing a generated QR code (I mean, something like an electronic poster where a QR code is surrounded by various texts).

**Comment by markusfisch** [comment]
Sorry, I don't quite understand - do you mean you want to scan a QR code from an image that is you on your phone? That's already possible: just share the image with Android's share menu. Binary Eye should be available within that menu for you to pick.
