### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by andrewshadura** [markusfisch/BinaryEye#60]
When scanning QR codes like [this](https://debconf19.debconf.org/static/img/dc19-schedule-qr-code.925b4c1a5024.png) in [Giggity](https://gaa.st/giggity), Binary Eye apparently tried to decode UTF-8 or something, so Giggity fails to ungzip the barcode.

**Comment by markusfisch** [comment]
Hm, I was able to unpack the QR code without problems 🤔

Did you use `gzip -d` to decode the binary contents? Did you save the file with the `gz` extension? Zip can't decode gzip's `gz` format so if you used `your_file.zip` it won't work.

I used `gzip` in [Termux](https://play.google.com/store/apps/details?id=com.termux) to unpack the file I saved from Binary Eye.

**Comment by andrewshadura** [comment]
I'm using Giggity directly, and it works with Barcode Scanner but not with
Binary Eye.

>

**Comment by andrewshadura** [comment]
[This QR code](https://lvee-wafer.shadura.me/static/img/dc19-schedule-qr-code.png) is one I’m having issues with specifically.

**Comment by markusfisch** [comment]
Again, I can read and unpack this QR code without problems using the same workflow:

1. Scan QR code with Binary Eye
2. Save the read binary data by tapping the Floating Action Button in the lower right corner
3. When Binary Eye asks for a filename, I gave `t.gz`
4. Open Termux and `cd /sdcard/Download`
5. `gzip -d t.gz`
6. `less t`

This is what I get:
```
{
  "version": 2018083000,
  "url": "https://lvee-wafer.shadura.me/schedule/pentabarf.xml",
  "title": "LVEE 2019",
  "start": "2019-08-22",
  "end": "2019-08-25",
  "metadata": {
    "icon": "https://lvee.org/uploads/image_upload/file/172/lvee_logo_160x155.png",
    "links": [
      {
        "url": "https://lvee.org/",
        "title": "Website"
      }
    ]
  }
}
```

So, what is your workflow? What do you mean by you're using Giggity directly? Does Giggity open Binary Eye and you're never saving the data as a file?

**Comment by andrewshadura** [comment]
Yes, I press "Scan QR" in Giggity, it calls out to Barcode Scanner/Binary Eye and gets the data back. I’m not quite sure, maybe there’s a bug in Giggity, or maybe the data are returned in slightly different ways from Binary Eye and Barcode Scanner? Maybe when you create the reply intent, something goes wrong?

**Comment by markusfisch** [comment]
Ah, now I understand! And you're right! The resulting Intent contained only the interpreted string representation of the scanned code.

I've added all other fields from the original ZXing Android client and built a new beta version 1.13.0 that should be available in the next few hours.

You can try it by becoming a Beta tester here:
https://play.google.com/apps/testing/de.markusfisch.android.binaryeye

You can always go back to the production version. If you want, you can also install the APK directly from here:
https://github.com/markusfisch/BinaryEye/releases/tag/1.13.0
