### ISSUE TITLE
Android 4.1.2 is compatible

### ISSUE THREAD

**Issue by anewuser** [markusfisch/BinaryEye#68]
F-Droid says that Binary Eye 1.14.0 is incompatible with Android 4.1.2, but I installed it on such a device, and it works as expected. You may want to lower down the minimum required version.

**Comment by molikuner** [comment]
Actually it's quite low ([9](https://github.com/markusfisch/BinaryEye/blob/ca619efa146f47547f261db4f450f0bc5d86753d/app/build.gradle#L9)). This means, that this isn't the reason why F-Droid thinks it's incompatible. Which device specifically has the issue?

**Comment by anewuser** [comment]
I see, sorry. It's an [LG E410](https://www.lg.com/uk/mobile-phones/lg-E410). I assumed that was the case because the other two applications that I tested on it were indeed incompatible.

**Comment by kekukui** [comment]
Same issue exists on Amazon Fire OS tablets (typically runs Android 5 or greater).  Marked as incompatible in F-Droid app, but it still works.
