### ISSUE TITLE
Doesn't display binary

### ISSUE THREAD

**Issue by MarkJeronimus** [markusfisch/BinaryEye#7]
I hoped this would live up to it's name and display binary or hexadecimal data from a 'binary data' QR code (like the ones from Signal messenger) but it renders the data as a garbled string.

**Comment by markusfisch** [comment]
Actually, that's an interesting idea 🤔

**Comment by markusfisch** [comment]
Implemented in https://github.com/markusfisch/BinaryEye/commit/1e3f1c553cd78e351d669f236bfe0192375586c6

Available in 1.5.0 currently in Beta. You may opt-in for Beta builds here:
https://play.google.com/apps/testing/de.markusfisch.android.binaryeye
