### ISSUE TITLE
Feature request: Share contacts

### ISSUE THREAD

**Issue by nilsjor** [markusfisch/BinaryEye#73]
It would be nice to choose "Binary Eye" as an option when sharing a contact, similar to how Huawei shows a QR code when viewing a contact.

**Comment by markusfisch** [comment]
Yes, good idea! Put it on the list.

**Comment by molikuner** [comment]
We should implement a abstract way for that. This would simplify the code later when we implement the option to share a calendar event, website, etc. to BinaryEye.
Probably we should even rewrite the current implementation for images at that point to also use this new abstraction.

**Comment by TheLastGimbus** [comment]
Hey @markusfisch, how is this going? BinaryEye is the lightest, fastest and generally ,*best* qr scanner I know, and I still can't quickly add a contact with it - it's kinda embarrassing 😬

**Comment by markusfisch** [comment]
@TheLastGimbus Sorry about this 😬

May I ask if you _scanned_ a QR Code with a contact (probably a `VCARD`?) and Binary Eye wasn't able to add it to your contacts?

Or did you want to _create_ a QR code from one of your contacts?

**Comment by TheLastGimbus** [comment]
Someone shared a QR contact with me and I had to manualy copy paste the number

But when I click on "share" in my contacts app, and it shares a `.vcf` file, BinaryEye also *doesn't* appear on the list

**Comment by markusfisch** [comment]
Again, sorry for this inconvenience. Adding a contact from a QR Code should definitely work. After checking this feature on a couple of my devices today, I found out that this is no longer working on Android 11 😬  Unfortunately, I've got no idea what's the reason and the [docs](https://developer.android.com/training/contacts-provider/modify-data#InsertEdit) are silent on this change 🤷‍♂️  So I'm on it.

Sharing a contact with a QR Code is a different feature which isn't implemented yet.

**Comment by TheLastGimbus** [comment]
Oh, I scanned some code from Google, and it works! But when I tried this with my friend it didn't... weird...

**Comment by markusfisch** [comment]
Hm 🤔 Did the content of the QR Code of your friend start with `BEGIN:VCARD`? Do you have a sample for me?

Besides, I found the reason why adding contacts stopped working on Android 11 and was able to fix it in https://github.com/markusfisch/BinaryEye/commit/49d32ff95cba2a202a7a257aab21e628a8c7cf95
So this will be working again with the next release 😄

Thanks for filing an issue and bringing my attention to this problem 👍

**Comment by zenlord** [comment]
This app caught my eye ;). I like it a lot!

I believe this feature request is the one I'm interested in as well. The way to implement it, as I see it, is
1. to register the app to accept content being shared with it,
2. When the app is being called by the Sharing API, to redirect the content into the 'content' field of the 'create new barcode' screen.

Using this API, every app could 'export' data to Binary Eye, including contacts, events, maybe also WiFi access.

**Comment by TheLastGimbus** [comment]
Sorry for not responding to this long - for me, **adding** a contanct **from** qr code works well! However, sharing it (which this issue actually is for), does not :( - i know this should be built into the contacts app itself, but it's not always, so would be nice for BinaryEye to have!

**Comment by markusfisch** [comment]
Yes, agreed, a way to share contacts directly from Binary Eye would be nice. Put it on the list.Adding contacts from barcodes should work fine already as long as the VCARD format is used.Am 13.06.2023 16:18 schrieb Mateusz Soszyński ***@***.***>:
Sorry for not responding to this long - for me, adding a contanct from qr code works well! However, sharing it (which this issue actually is for), does not :( - i know this should be built into the contacts app itself, but it's not always, so would be nice for BinaryEye to have!

**Comment by fanis** [comment]
Looking forward to this feature. I've been using Binary Eye on older devices to scan, would love to use it to share contacts too.
