### ISSUE TITLE
Issue: Creating new Barcode, I get always the first one I've ever created

### ISSUE THREAD

**Issue by metadings** [markusfisch/BinaryEye#82]
Look. If I create a new barcode and I'm just going to share/export into a "Simple Draw" (Zeichenblock) app, I do get always the image for "http://schlüsseldienst-frickenhausen.de", an address which I've made once (I know this should've been "//xn--schlusseldienst-frickenhausen-46c.de").
Now if I'm trying to make a new image for example for "https://github.com/metadings", this exported to my Draw app, I do always get the stupid OLD image !

(There is the file `intern/Android/data/de.markusfisch.android.binaryeye/cache/shared_barcode.png` which I can copy to somewhere else :smiley_cat:)

**Comment by markusfisch** [comment]
That's really odd - and I can't reproduce it, unfortunately 🤔 I just checked it on two devices (Pixel 2 on Android 10 and a Nexus Robin with Android 7.1.1) and the latest generated barcode is always shared correctly 🤷‍♂ 

So, I'm afraid I have no idea what's going wrong 😬 What makes this issue all the more important to me. After all, you may not be alone with that bug so thanks a lot for reporting it!

In order to understand what is going wrong, I need a litte more info:
* Does the file `shared_barcode.png` hold the latest generated/shared barcode or always the first? 
* Does it fix the problem if you delete `shared_barcode.png` (don't worry, it's recreated when you share a barcode)?
* What are the file modes of `shared_barcode.png`?

**Comment by metadings** [comment]
- Does the file shared_barcode.png hold the latest generated/shared barcode or always the first?
The file holds the latest generated barcode

- Does it fix the problem if you delete shared_barcode.png (don't worry, it's recreated when you share a barcode)?
It is recreated, but no, this doesn't fix it.

- What are the file modes of shared_barcode.png?
Well I don't know, my File managers don't tell me

I do want to encourage you, to just do just "Save File as" instead of "Share"/export to another app. I do have just the Draw app to save images, the export command gives me "Telegram", "Play with VLC", "Barcode decodieren", "SecScanQR", "Scanner", "Nachrichten/Messages", "Bluetooth", "Notizen/Notes", "Rückmeldung/Feedback", "Mi Drop", "A Photo Viewer", "Google Photos", "Google Drive", "Google Maps", "Gmail",
instead of just "Save as" PNG or JPG

**Comment by markusfisch** [comment]
Sorry, I don't quite get it yet 🙈  What do you mean by "Save File as"? The only option to export the barcode is to share with the floating action button in the lower right corner, right?

Or did you mean "Save File as" as an option _in_ the share menu?

**Comment by metadings** [comment]
> The only option to export the barcode is to share with the floating action button in the lower right corner, right?
Yes... I think there should be an option, a new button just for "Save as" File

**Comment by markusfisch** [comment]
Ah, okay, understood 👍 

But what about the bug - you're still getting the wrong barcode when you share it with said floating action button. Is that correct?

For a quick fix about that "Save as" button: some file managers (e.g. the [Amaze File Manager](https://play.google.com/store/apps/details?id=com.amaze.filemanager&hl=en) do add a "Save as" entry for images in the share menu that allows you to save a shared image as a file.

**Comment by metadings** [comment]
> But what about the bug - you're still getting the wrong barcode when you share it with said floating action button. Is that correct?

No ! With Amaze file manager's "Save as" this is working !!

I've created a new barcode now, QR-CODE, 256x256, https://github.com/metadings ...
Yeah, I don't use Play... I'm using F-Droid and well I do have "Amaze" "Save as"!
Other File Managers are not displayed by this "export" or "share" command.
However, you shouldn't expect people to have this "Amaze" file manager !
In fact, I believe nobody has this one, which is really the only one just "Save as"... otherwise, as you can see above what apps are displayed if I'm "sharing" this image.
You do really, really need just "Save as" JPG or PNG!

(Also the rectangle of which is later the image, you do have to crop a lot to have just a barcode for example in LibreOffice Writer or just GIMP/Paint.)

**Comment by metadings** [comment]
YEAH :+1: This is awesome :cat:

[I'm going to insert screenshots here]

Now there should also be an additional
- What FileName do you want to use?  (shared_barcode.png...)
- Do you really want to overwrite (shared_barcode.png...)? (Yes/No)

**Comment by metadings** [comment]
![Creating a new Barcode, QR-CODE, 512x512 ...](https://user-images.githubusercontent.com/1684098/68879179-43187d80-0709-11ea-898c-5f6295e65eba.jpg)
![Viewing the new Barcode...](https://user-images.githubusercontent.com/1684098/68879180-43187d80-0709-11ea-9414-c69b760b19a0.jpg)
![Saving the new Barcode 1](https://user-images.githubusercontent.com/1684098/68879181-43b11400-0709-11ea-9f6f-b29748fbd08f.jpg)
![Saving the new Barcode 2](https://user-images.githubusercontent.com/1684098/68879182-43b11400-0709-11ea-90a6-51d9c87a288b.jpg)
![Saving the new Barcode 3](https://user-images.githubusercontent.com/1684098/68879183-43b11400-0709-11ea-8c8f-50ab8aa8c2c7.jpg)
![amaze! filemanager](https://user-images.githubusercontent.com/1684098/68879184-4449aa80-0709-11ea-8c77-56a4f39df0c8.jpg)
