### ISSUE TITLE
Feature Request: Scan Barcodes in Files

### ISSUE THREAD

**Issue by metadings** [markusfisch/BinaryEye#83]
Scan Barcodes not just from the Camera,
but also from Image Files `/sd-card/DCIM/Camera/IMG_2019-11-16_*.jpg` !

**Comment by metadings** [comment]
"Bilddatei auswählen"... I've just updated my F-Droid... This is so awesome. :+1: 
(You've just missed the "back" button in "Code scannen", nothing happens ...)

**Comment by markusfisch** [comment]
Fixed the defect up navigation (the back arrow beside the title) in https://github.com/markusfisch/BinaryEye/commit/80afd0c5b789ddc8d4800016fae7ab89b0a48f08
Thanks for the catch! 👍 

About the order of barcodes; they're sorted alphabetically at the moment. But I am considering to change this order. I'm just not sure what would be the best order yet.

Version 1.18.0 should become available in the next few hours on Google Play.

Or fetch the APK directly from here: https://github.com/markusfisch/BinaryEye/releases

**Comment by metadings** [comment]
> they're sorted alphabetically

That's okay, I would just set the default selected item to QR-CODE.

**Comment by markusfisch** [comment]
Version 1.19.0 will always remember the last selected barcode format now (see https://github.com/markusfisch/BinaryEye/commit/83619834a8af2b6f5da18c804968190a47f05e7c)
