### ISSUE TITLE
Feature request: allow zoom out on created codes

### ISSUE THREAD

**Issue by fgaz** [markusfisch/BinaryEye#85]
Some code readers (on buses for example) cannot read the code if it's too big, so I have to save the image, open it with another application, and them zoom it out. It would be nice if we could zoom out directly on the code preview (zoom in is already possible)

**Comment by markusfisch** [comment]
Implemented in https://github.com/markusfisch/BinaryEye/commit/7f3af23773194b905cf19b6c1514fe1884b5b658

Comes with the next release! 😄

**Comment by fgaz** [comment]
Wow, that was fast! Thank you so much!
