### ISSUE TITLE
update readme and fastlane descriptions to include creation and more features

### ISSUE THREAD

**Issue by jmichael2497** [markusfisch/BinaryEye#87]
the readme and fastlane descriptions need updates, since apparently this has had the ability to create images since almost the first version, but the description still says "doesn't do much else but decoding a barcode" so i've ignored it, until recently glancing at the picture having a "compose" screen.

i've been using the zxing barcode scanner app (which can read various codes and create only qr codes), but they are not going to update their app to target current apis as required by official app store (though i screen apps by checking for dual f-droid/play store availability), so...

i'm looking for alternative foss replacements, i like that you specify the library you use (currently zxing), what you are able to read (and apparently able to create?).

maybe also list examples of usage, especially useful for not having to type in a long website, swapping contact cards, sharing wifi name and password... once you add matching features like the original zxing app.

hope that helps.

**Comment by urbalazs** [comment]
This metadata would make it possible to get localize package descriptions in app stores, for example in F-Droid. Here is the [documentation](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-apps-build-metadata-in-an-fdroiddata-collection) and an [example app](https://github.com/k3b/ToGoZip/tree/master/fastlane/metadata/android/en-US).

Please provide these files in this repo.

**Comment by markusfisch** [comment]
I've updated the description and the metadata is now in https://github.com/markusfisch/BinaryEye/tree/master/metadata/en-US
