### ISSUE TITLE
Can't create any barcodes

### ISSUE THREAD

**Issue by EauBureau** [markusfisch/BinaryEye#89]
Hi,

I can't create any barcodes. 
The app crashes with "Unfortunately, Binary Eye has stopped".

I'm not a developer at all, but I took a look with `adb logcat` and found this for the crash

`E/AndroidRuntime( 7564): FATAL EXCEPTION: main
E/AndroidRuntime( 7564): java.lang.ClassCastException: android.support.v7.widget.c1 cannot be cast to android.support.v7.app.d
`

Android 4.1.2
BinaryEye 1.19.0

Thanks.

**Comment by markusfisch** [comment]
Hi, sorry for the crash and sorry for answering so late. I found the bug and I'm going to fix it with the next version.

**Comment by EauBureau** [comment]
That's great. Thanks for the fix, and thanks for BinaryEye too :thumbsup:
