### ISSUE TITLE
Weblate integration

### ISSUE THREAD

**Issue by urbalazs** [markusfisch/BinaryEye#91]
Hello @markusfisch 
did you ever think about the integration of an online translation system like for example [Weblate](https://hosted.weblate.org/)?
This is free for open source non-commercial projects. Weblate can automatically push translation changes directly into your GitHub repository. This would make it possible to involve more translators who have no git knowledge.

**Comment by markusfisch** [comment]
Yes, I once used a similar service in the past. Forgot the name. But it didn't work too well so I lost track of it.

But Weblate looks really nice and I would like to give it a try! Unfortunately, it seems that I'm not permitted to create a new project 😬 Apparently, they don't provide this service for free anymore - even for open source non-commercial projects like this one 🤷‍♂

**Comment by Wilker-a** [comment]
weblate is [free software](https://www.gnu.org/philosophy/free-sw.html), which means that you have the right to run it yourself if you want, and also on a server if you have somewhere to host an instance on. maybe you can figure something out with that?

**Comment by urbalazs** [comment]
Is there any progress here, or can I close this issue? It seams, that this project has many translations without using Weblate, so maybe it is not needed.

**Comment by markusfisch** [comment]
To be honest, I think it's too much of a hassle 😬 So yes, the issue can be closed. I just kept it open to see how much it is desired 😉

**Comment by inson1** [comment]
@markusfisch Weblate has free hosting for open source projects. What about reopening this?

**Comment by markusfisch** [comment]
@yurtpage Thanks for the PR! And sorry for the late response. I just merged #519.
