### ISSUE TITLE
Calling Binary Eye from other apps stopped working [still doesn't work]

### ISSUE THREAD

**Issue by di72nn** [markusfisch/BinaryEye#92]
#84 still seems to be present.

// I don't have permissions to reopen #84, hence a new issue.

**Comment by markusfisch** [comment]
Sorry for that - I guess I blew that last time 😬 

Please try version 1.20.0 which should become available shortly in beta:
https://play.google.com/apps/testing/de.markusfisch.android.binaryeye

Or you may try the APK directly from GitHub:
https://github.com/markusfisch/BinaryEye/releases/tag/1.20.0

I'll leave this issue open to see if it's working for you.

**Comment by di72nn** [comment]
It's working now. Thank again!
