### ISSUE TITLE
Opening image files from file manager does not work

### ISSUE THREAD

**Issue by SebiderSushi** [markusfisch/BinaryEye#93]
### Expected behavior
When opening an image file, BinaryEye should be one of the apps available for selection and, if chosen, decode any supported codes within the image file to text.

### Actual behavior
I'm running Android 8.1.0 and BinaryEye 1.20.1
When opening an image file, the native Android "open-with" application picker does not include BinaryEye.

In the (proprietary) file manager FX (`nextapp.fx`), there is a built in "open-with" application picker. It shows an entry for BinaryEye [which is why i'd expect it to support opening a file this way]. Howerver, the entry is marked with a red x-icon and, once tapped, triggers a message that reads: "The selected app does not support opening this item using a "Content URI". As of late 2018 Google has required apps to only use Content URIs for opening files. You may need to update the target application or contact its developer."

### Proposed solution
Is it possible to implement Content URI support in BinaryEye?

**Comment by markusfisch** [comment]
Thanks for the issue 👍 Yes, it should be possible to implement the necessary support in Binary Eye - although I'm not really sure what FX is trying to do exactly 😬 

I've tried to open an image from FX but all I see is the "Share" option. And there I see Binary Eye.
So, what do you mean by "the native Android open-with application picker"? How do you open an image in FX for another application?

**Comment by SebiderSushi** [comment]
By "the native Android open-with application picker" i mean [this dialog](https://i.stack.imgur.com/NP5nx.png) (at least on android 6 and above that's what it looks like). On my device (ROM based on Lineage 15.1) there is a preinstalled "Files" app. If i try opening an image file from within that it would trigger said dialog. There is also an option labeled "Open with" when selecting a file in FX. On my device, the native "open with" dialog offers to choose from the preinstalled Gallery app and the "FX Image Viewer" while the "open with" dialog within FX also lists BinaryEye. Given the warning issued by FX, i'd guess that the native dialog simply filters out BinaryEye due to its alleged incompatibility with Google/Android guidelines.

I think what happens in these cases is that an intent with android.intent.action.VIEW is started, but i'm not deep into anything concerning Content Providers or URIs.

However, now that you've mentioned that i might just as well share an image to Binary Eye, i can easily live with that. It even makes more sense since a user might want to choose their favorite gallery app as a default handler of such file opening intents, wheras BinaryEye will still be available under the share menu.
I just never looked in there since my understanding of "share" implies an action that's supposed to send things to others and i would have expected the barcode decryption activity to be available when opening a file, but now that i know about the sharing option, i'd consider this issue fixed.

**Comment by SebiderSushi** [comment]
Otherwise, from the Android Developer Guide about Intents, i think [this](https://developer.android.com/guide/components/intents-filters#Resolution) is the section relevant to this topic of Content URIs.
It seems to me that the issue would be connected to declaring the scheme "file" in [this line](https://github.com/markusfisch/BinaryEye/blob/master/app/src/main/AndroidManifest.xml#L67) in BinaryEye's manifest.

**Comment by markusfisch** [comment]
You're right! Simply removing the file scheme from the intent filter made it work for me!
So, hopefully, it's fixed in https://github.com/markusfisch/BinaryEye/commit/1223bd36790c8bc3480228be10f53304c8cd060e

I checked it on Android 4, 7, 9 and 10 with Google Drive and the mentioned Files app and I'm getting Binary Eye as an option for "Open with" now. Thanks a lot for finding it out 👍

Version 1.21.0 should become available shortly, as usual first in the beta channel. You can opt in here (you can always opt-out and go back to the production version):
https://play.google.com/apps/testing/de.markusfisch.android.binaryeye

Alternatively, you can grab the latest APK directly from GitHub here:
https://github.com/markusfisch/BinaryEye/releases/tag/1.21.0

**Comment by SebiderSushi** [comment]
Sweet!
Since i don't use Google Play i have tried the APK from the releases page and it works for me as well.
Now waiting for the update to be published by F-Droid. Thank you for fixing :)
